<?php

return [
    'file-manager' => 'Gestionnaire de fichiers',
    'search' => 'Rechercher',
    'delete' => 'Supprimer',
    'move' => 'Déplacer',
    'archive' => 'Archiver',
    'unarchive' => 'Désarchiver',
    'create-directory' => 'Créer un répertoire',
    'upload' => 'Téléverser', ##Terme correct mais pourrais utiliser le terme 'Envoyer'
    'new-file' => 'Nouveau fichier',
    'rename' => 'Renommer',
    'permissions' => 'Permissions',
    'copy' => 'Copier',
    'download' => 'Télécharger',
    'update' => 'Mettre à jour',
    'file-mode' => 'Mode du fichier',
    'you-cant-recover' => 'Vous ne pourrez pas récupérer le contenu de',
    'once-deleted' => 'une fois supprimé.',
    'delete-files' => 'Supprimer les fichiers',
    'are-you-sure' => 'Êtes-vous sûr de vouloir supprimer',
    'this-is-permanent-action' => 'Il s\'agit d\'une action permanente et les fichiers ne pourront pas être récupérés.',
    'name' => 'Nom',
    'size' => 'Taille',
    'date' => 'Date',
    'home' => 'Accueil',
    'container' => 'Conteneur',
    'is-empty' => 'Ce répertoire semble être vide.',
    'is-limited' => 'Ce répertoire est trop volumineux pour être affiché dans le navigateur. La sortie est limitée aux 250 premiers fichiers.',
    'are-upload-click-to-view' => 'des fichiers sont en cours de téléversement, cliquez pour voir',
    'cancel-uploads' => 'Annuler les téléversements',
    'cancel' => 'Annuler',
    'close' => 'Fermer',
    'create' => 'Créer',
    'file-name' => 'Nom du fichier',
    'file-name-description' => 'Saisissez le nom sous lequel ce fichier doit être enregistré.',
    'directory-will-be-as' => 'Ce répertoire sera créé en tant que',
    'rename-description' => 'Saisissez le nouveau nom et le répertoire de ce fichier ou dossier, par rapport au répertoire actuel.',
    'new-location' => 'Nouvel emplacement',
    'drag-and-drop' => 'Faites glisser et déposez des fichiers pour les téléverser.',

    'edit' => [
        'youre-editing' => 'Vous modifiez un',
        'will-be-exluded' => 'fichier. Tous les fichiers ou répertoires répertoriés ici seront exclus des sauvegardes. Les exceptions sont pris en charge en utilisant un astérisque',
        'you-can-negate' => 'Vous pouvez nier une règle précédente en préfixant un point d\'exclamation',
        'save-content' => 'Enregistrer le contenu',
        'create-file' => 'Créer un fichier',
    ],
];
