<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Iniciando',
    'stopping' => 'Parando',
    'suspended' => 'Suspenso',
    'connection-error' => 'Erro de Conexão',
    'transferring' => 'Transferindo',
    'installing' => 'Instalando',
    'restoring-backup' => 'Restaurando Backup',
    'unavailable' => 'Indisponível',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Memória',
    'disk' => 'Disco',
    'unlimited' => 'Ilimitado',
    'start' => 'Iniciar',
    'restart' => 'Reiniciar',
    'stop' => 'Parar',
    'kill' => 'Forçar Parada',
    'forcibly-stop-process' => 'Parar Processo Forçadamente',
    'continue' => 'Continuar',
    'forcibly-stopping-alert' => 'Forçar a parada de um servidor pode levar à corrupção de dados.',
    'cpu-usage' => 'Uso de CPU',
    'memory-usage' => 'Uso de Memória',
    'disk-usage' => 'Uso de Disco',
    'inbound-outbound' => 'Entrada / Saída',
    'low-resources' => 'Recursos Baixos',
    'low-resources-desc' => 'Seu servidor está com poucos recursos, certifique-se de atualizar seu plano',
    'upgrade-server' => 'Atualizar Servidor',
    'cancel' => 'Cancelar',
    'copied-text' => 'Copiado {{text}} para a área de transferência.',
    'showing' => 'Mostrando',
    'to' => 'a',
    'of' => 'de',
    'results' => 'resultados.',
];
