<?php

return [
    'online' => 'オンライン',
    'offline' => 'オフライン',
    'starting' => '起動中',
    'stopping' => '停止中',
    'suspended' => '停止',
    'connection-error' => '接続エラー',
    'transferring' => '转送中',
    'installing' => 'インストール中',
    'restoring-backup' => 'バックアップを復元中',
    'unavailable' => '利用不可',
    'status' => 'ステータス',
    'CPU' => 'CPU',
    'memory' => 'メモリ',
    'disk' => 'ディスク',
    'unlimited' => '無制限',
    'start' => '起動',
    'restart' => '再起動',
    'stop' => '停止',
    'kill' => '強制終了',
    'forcibly-stop-process' => 'プロセスを強制停止',
    'continue' => '続行',
    'forcibly-stopping-alert' => 'サーバーを強制停止するとデータが損傷する可能性があります。',
    'cpu-usage' => 'CPU使用率',
    'memory-usage' => 'メモリ使用率',
    'disk-usage' => 'ディスク使用率',
    'inbound-outbound' => '受信 / 送信',
    'low-resources' => 'リソース不足',
    'low-resources-desc' => 'サーバーのリソースが不足しています。プランをアップグレードしてください',
    'upgrade-server' => 'サーバーをアップグレード',
    'cancel' => 'キャンセル',
    'copied-text' => '{{text}}をクリップボードにコピーしました。',
    'showing' => '表示中',
    'to' => '〜',
    'of' => '／',
    'results' => '件。',
];