<?php

return [
    'online' => 'En línea',
    'offline' => 'Fuera de línea',
    'starting' => 'Iniciando',
    'stopping' => 'Deteniendo',
    'suspended' => 'Suspendido',
    'connection-error' => 'Error de conexión',
    'transferring' => 'Transfiriendo',
    'installing' => 'Instalando',
    'restoring-backup' => 'Restaurando copia de seguridad',
    'unavailable' => 'No disponible',
    'status' => 'Estado',
    'CPU' => 'CPU',
    'memory' => 'Memoria',
    'disk' => 'Disco',
    'unlimited' => 'Ilimitado',
    'start' => 'Iniciar',
    'restart' => 'Reiniciar',
    'stop' => 'Detener',
    'kill' => 'Forzar detención',
    'forcibly-stop-process' => 'Forzar detención del proceso',
    'continue' => 'Continuar',
    'forcibly-stopping-alert' => 'Forzar la detención de un servidor puede provocar corrupción de datos.',
    'cpu-usage' => 'Uso de CPU',
    'memory-usage' => 'Uso de memoria',
    'disk-usage' => 'Uso de disco',
    'inbound-outbound' => 'Entrante / Saliente',
    'low-resources' => 'Bajos recursos',
    'low-resources-desc' => 'Tu servidor tiene bajos recursos, asegúrate de actualizar tu plan',
    'upgrade-server' => 'Actualizar servidor',
    'cancel' => 'Cancelar',
    'copied-text' => '{{text}} copiado al portapapeles.',
    'showing' => 'Mostrando',
    'to' => 'a',
    'of' => 'de',
    'results' => 'resultados.',
];
