<?php

return [
    'file-manager' => 'Gestor de archivos',
    'search' => 'Buscar',
    'delete' => 'Eliminar',
    'move' => 'Mover',
    'archive' => 'Archivar',
    'unarchive' => 'Desarchivar',
    'create-directory' => 'Crear directorio',
    'upload' => 'Subir',
    'new-file' => 'Nuevo archivo',
    'rename' => 'Renombrar',
    'permissions' => 'Permisos',
    'copy' => 'Copiar',
    'download' => 'Descargar',
    'update' => 'Actualizar',
    'file-mode' => 'Modo de archivo',
    'you-cant-recover' => 'No podrás recuperar el contenido de',
    'once-deleted' => 'una vez eliminado.',
    'delete-files' => 'Eliminar archivos',
    'are-you-sure' => '¿Estás seguro de que quieres eliminar',
    'this-is-permanent-action' => 'Esta es una acción permanente y los archivos no se pueden recuperar.',
    'name' => 'nombre',
    'size' => 'tamaño',
    'date' => 'fecha',
    'home' => 'inicio',
    'container' => 'contenedor',
    'is-empty' => 'Este directorio parece estar vacío.',
    'is-limited' => 'Este directorio es demasiado grande para mostrar en el navegador, limitando la salida a los primeros 250 archivos.',
    'are-upload-click-to-view' => 'archivos se están subiendo, haz clic para ver',
    'cancel-uploads' => 'Cancelar subidas',
    'cancel' => 'Cancelar',
    'close' => 'Cerrar',
    'create' => 'Crear',
    'file-name' => 'Nombre de archivo',
    'file-name-description' => 'Ingresa el nombre con el que se debe guardar este archivo.',
    'directory-will-be-as' => 'Este directorio se creará como',
    'rename-description' => 'Ingresa el nuevo nombre y directorio de este archivo o carpeta, en relación con el directorio actual.',
    'new-location' => 'Nueva ubicación',
    'drag-and-drop' => 'Arrastra y suelta archivos para subir.',

    'edit' => [
        'youre-editing' => 'Estás editando un',
        'will-be-exluded' => 'archivo. Cualquier archivo o directorio listado aquí será excluido de las copias de seguridad. Se admiten comodines utilizando un asterisco',
        'you-can-negate' => 'Puedes negar una regla anterior anteponiendo un signo de exclamación',
        'save-content' => 'Guardar contenido',
        'create-file' => 'Crear archivo',
    ],
];
