<?php

return [
    'online' => 'En ligne',
    'offline' => 'Hors ligne',
    'starting' => 'Démarrage en cours',
    'stopping' => 'Arrêt en cours',
    'suspended' => 'Suspendu',
    'connection-error' => 'Erreur de connexion',
    'transferring' => 'Transfert en cours',
    'installing' => 'Installation en cours',
    'restoring-backup' => 'Restauration de la sauvegarde',
    'unavailable' => 'Non disponible',
    'status' => 'Statut',
    'CPU' => 'CPU', ##Processeur pourrait être utiliser
    'memory' => 'Mémoire',
    'disk' => 'Disque',
    'unlimited' => 'Illimité',
    'start' => 'Démarrer',
    'restart' => 'Redémarrer',
    'stop' => 'Arrêter',
    'kill' => 'Forcer l\'arrêt',
    'forcibly-stop-process' => 'Arrêt forcé du processus',
    'continue' => 'Continuer',
    'forcibly-stopping-alert' => 'Forcer l\'arrêt d\'un serveur peut entraîner une corruption des données.',
    'cpu-usage' => 'Utilisation du CPU',
    'memory-usage' => 'Utilisation de la mémoire',
    'disk-usage' => 'Utilisation du disque',
    'inbound-outbound' => 'Entrant / Sortant',
    'low-resources' => 'Ressources faibles',
    'low-resources-desc' => 'Votre serveur manque de ressources, Vous pourriez envisagez d\'améliorer votre offre.',
    'upgrade-server' => 'Mettre à niveau le serveur',
    'cancel' => 'Annuler',
    'copied-text' => 'Copié {{text}} dans le presse-papiers.',
    'showing' => 'Affichage de',
    'to' => 'à',
    'of' => 'de',
    'results' => 'résultats.',
];
