<?php

return [
    'file-manager' => 'Filhanterare',
    'search' => 'Sök',
    'delete' => 'Radera',
    'move' => 'Flytta',
    'archive' => 'Arkivera',
    'unarchive' => 'Avarkivera',
    'create-directory' => 'Skapa Mapp',
    'upload' => 'Ladda Upp',
    'new-file' => 'Ny Fil',
    'rename' => 'Döp Om',
    'permissions' => 'Behörigheter',
    'copy' => 'Kopiera',
    'download' => 'Ladda Ner',
    'update' => 'Uppdatera',
    'file-mode' => 'Filläge',
    'you-cant-recover' => 'Du kommer inte att kunna återställa innehållet i',
    'once-deleted' => 'en gång raderad.',
    'delete-files' => 'Radera Filer',
    'are-you-sure' => 'Är du säker att du vill radera',
    'this-is-permanent-action' => 'Detta är en permanent åtgärd och filerna kan inte återställas.',
    'name' => 'namn',
    'size' => 'storlek',
    'date' => 'datum',
    'home' => 'hem',
    'container' => 'container',
    'is-empty' => 'Den här mappen verkar vara tom.',
    'is-limited' => 'Den här mappen är för stor för att visas i webbläsaren, vilket begränsar utdata till de första 250 filerna.',
    'are-upload-click-to-view' => 'filer laddas upp, klicka för att visa',
    'cancel-uploads' => 'Avbryt Uppladdningar',
    'cancel' => 'Avbryt',
    'close' => 'Stäng',
    'create' => 'Skapa',
    'file-name' => 'Fil Namn',
    'file-name-description' => 'Ange namnet som filen ska sparas som.',
    'directory-will-be-as' => 'Denna mapp kommer att skapas som',
    'rename-description' => 'Ange det nya namnet och mappen för denna fil eller mapp, i förhållande till den aktuella katalogen.',
    'new-location' => 'Ny plats',
    'drag-and-drop' => 'Dra och släpp filer för att ladda upp.',

    'edit' => [
        'youre-editing' => 'Du redigerar en',
        'will-be-exluded' => 'fil. Alla filer eller mappar som listas här kommer att uteslutas från säkerhetskopior. Wildcards stöds genom att använda en asterisk',
        'you-can-negate' => 'You can negate a prior rule by prepending an exclamation point',
        'save-content' => 'Spara Innehåll',
        'create-file' => 'Skapa Fil',
    ],
];
