<?php

return [
    'file-manager' => 'Filhanterare',
    'search' => 'Sök',
    'delete' => 'Radera',
    'move' => 'Flytta',
    'archive' => 'Arkivera',
    'unarchive' => 'Avarkivera',
    'create-directory' => 'Skapa Mapp',
    'upload' => 'Ladda Upp',
    'new-file' => 'Ny Fil',
    'rename' => 'Döp Om',
    'permissions' => 'Behörigheter',
    'copy' => 'Kopiera',
    'download' => 'Ladda Ner',
    'update' => 'Uppdatera',
    'file-mode' => 'Filläge',
    'you-cant-recover' => 'Du kommer inte att kunna återställa innehållet i',
    'once-deleted' => 'en gång raderad.',
    'delete-files' => 'Radera Filer',
    'are-you-sure' => 'Är du säker att du vill radera',
    'this-is-permanent-action' => 'Detta är en permanent åtgärd och filerna kan inte återställas.',
    'name' => 'namn',
    'size' => 'storlek',
    'date' => 'datum',
    'home' => 'hem',
    'container' => 'container',
    'is-empty' => 'Den här mappen verkar vara tom.',
    'is-limited' => 'Den här mappen är för stor för att visas i webbläsaren, vilket begränsar utdata till de första 250 filerna.',
    'are-upload-click-to-view' => 'filer laddas upp, klicka för att visa',
    'cancel-uploads' => 'Avbryt Uppladdningar',
    'cancel' => 'Avbryt',
    'close' => 'Stäng',
    'create' => 'Skapa',
    'file-name' => 'Fil Namn',
    'file-name-description' => 'Ange namnet som filen ska sparas som.',
    'directory-will-be-as' => 'Denna mapp kommer att skapas som',
    'rename-description' => 'Ange det nya namnet och mappen för denna fil eller mapp, i förhållande till den aktuella katalogen.',
    'new-location' => 'Ny plats',
    'drag-and-drop' => 'Dra och släpp filer för att ladda upp.',


    'folders-not-supported' => 'Uppladdning av mappar stöds för närvarande inte.',
    'upload-files' => 'Ladda upp filer',
    'folder-too-big' => 'Mappens storlek överskrider gränsen på 10 MB. Välj en mindre mapp.',
    'upload-folders' => 'Ladda upp mappar',
    'upload-from-url' => 'Ladda upp från URL',
    'filename' => 'Filnamn',
    'open-code-editor' => 'Öppna kodredigerare',

    'code-editor' => [
        'explorer' => 'Utforskaren',
        'reload' => 'Ladda om',
        'new' => 'Ny',
        'browse-files' => 'Bläddra bland filer',
        'save' => 'Spara',
        'save-dirty' => 'Spara *',
        'saving' => 'Sparar...',
        'no-file-selected' => 'Ingen fil vald',
        'no-files-found' => 'Inga filer hittades',
        'loading' => 'Laddar...',

        'file-be-created' => 'Den här filen kommer att skapas som',
    ],
    
    'edit' => [
        'youre-editing' => 'Du redigerar en',
        'will-be-exluded' => 'fil. Alla filer eller mappar som listas här kommer att uteslutas från säkerhetskopior. Wildcards stöds genom att använda en asterisk',
        'you-can-negate' => 'Du kan negera en tidigare regel genom att lägga till ett utropstecken',
        'save-content' => 'Spara Innehåll',
        'create-file' => 'Skapa Fil',
    ],
];
