<?php 

return [
    'schedules' => 'Schedules',
    'manage-schedules' => 'Hantera Scheman',
    'create-schedule' => 'Skapa Schema',
    'name' => 'Namn',
    'last-run-at' => 'Sista körningen kl',
    'next-run-at' => 'Nästa körning kl',
    'status' => 'Status',
    'active' => 'Aktiva',
    'inactive' => 'Inaktiv',
    'processing' => 'Bearbetar',
    'manage-schedule' => 'Hantera Scheman',
    'new-task' => 'Ny uppgift',
    'run-now' => 'Kör Nu',
    'editBtn' => 'Redigera',
    'n/a' => 'n/a',
    'never' => 'aldrig',

    'no-schedules' => 'Det finns inga scheman konfigurerade för den här servern.',
    'ignore-files-folders' => 'Ignorerar filer & mappar',
    'continues-on-failure' => 'Fortsätter vid misslyckande',
    'later' => 'senare',

    'minute' => 'Minut',
    'hour' => 'Timme',
    'day' => 'Dag',
    'week' => 'Vecka',
    'day-of-month' => 'Dag i månaden',
    'month' => 'Månad',
    'day-of-week' => 'Dag i veckan',

    'deleteTask' => [
        'title' => 'Bekräfta borttagning av uppgift',
        'description' => 'Är du säker på att du vill ta bort den här uppgiften? Denna åtgärd kan inte ångras.',
        'delete' => 'Radera Uppgift'
    ],
    'delete' => [
        'title' => 'Ta Bort Schema',
        'description' => 'Alla uppgifter kommer att tas bort och alla pågående processer kommer att avslutas.',
        'delete' => 'Radera'
    ],
    'edit' => [
        'title-1' => 'Redigera schema',
        'title-2' => 'Skapa nytt schema',

        'description' => 'Schemasystemet stöder användningen av Cronjob-syntax när man definierar när uppgifter ska börja köras. Använd fälten ovan för att ange när dessa uppgifter ska börja köras.',
        
        'name' => 'Schemanamn',
        'name-description' => 'En läsbar identifierare för detta schema.',
        'cheatsheet' => 'Visa Fuskblad',
        'cheatsheet-description' => 'Visa cron fuskblad för några exempel',
        'online-when-online' => 'Endast när servern är aktiv',
        'online-when-online-description' => 'Kör endast detta schema när servern är i driftläge.',
        'enabled' => 'Schema aktiverat',
        'enabled-description' => 'Detta schema kommer att köras automatiskt om det är aktiverat.',

        'save-changes' => 'Spara ändringar',
    ],
    'cheatsheet' => [
        'example' => 'Exempel',
        'every-5-minutes' => 'var :e minut',
        'every-hour' => 'varje timme',
        'hour-range' => 'timmars intervall',
        'once-a-day' => 'en gång om dagen',
        'every-monday' => 'varje måndag',
        'special-characters' => 'Speciella Karaktärer',
        'any-value' => 'något värde',
        'value-list-separator' => 'värdelistavgränsare',
        'range-values' => 'intervallvärden',
        'step-values' => 'stegvärden',
    ],
    'task' => [
        'message' => 'En säkerhetskopieringsuppgift kan inte skapas när serverns säkerhetskopieringsgräns är inställd på 0.',
        'edit-task' => 'Redigera Uppgift',
        'save-changes' => 'Spara Ändringar',
        'create-task' => 'Skapa Uppgift',
        'action' => 'Åtgärd',
        'send-command' => 'Skicka kommando',
        'send-power-action' => 'Skicka kraftåtgärd',
        'create-backup' => 'Skapa säkerhetskopiering',
        'offset' => 'Tidsförskjutning (i sekunder)',
        'offset-description' => 'Hur lång tid det tar att vänta efter att den föregående uppgiften har körts innan den här körs. Om detta är den första uppgiften på ett schema kommer detta inte att tillämpas.',
        'payload' => 'Data Last',
        'ignored-files' => 'Ignorerade Filer',
        'ignored-files-description' => 'Frivillig. Inkludera filerna och mapparna som ska uteslutas i denna säkerhetskopia. Som standard kommer innehållet i din .pteroignore-fil att användas. Om du har nått din säkerhetskopieringsgräns kommer den äldsta säkerhetskopian att roteras.',
        'start-server' => 'Starta servern',
        'stop-server' => 'Stoppa servern',
        'restart-server' => 'Starta om servern',
        'kill-server' => 'Döda servern',
        'continue-on-failure' => 'Fortsätt vid fel',
        'continue-on-failure-description' => 'Framtida uppgifter kommer att köras när denna uppgift misslyckas.',
    ],
];
