<?php

return [
    'file-manager' => 'Dateimanager',
    'search' => 'suchen',
    'delete' => 'löschen',
    'move' => 'verschieben',
    'archive' => 'archivieren',
    'unarchive' => 'entpacken',
    'create-directory' => 'Verzeichnis erstellen',
    'upload' => 'hochladen',
    'new-file' => 'Neue Datei',
    'rename' => 'umbenennen',
    'permissions' => 'Berechtigungen',
    'copy' => 'kopieren',
    'download' => 'herunterladen',
    'update' => 'aktualisieren',
    'file-mode' => 'Dateimodus',
    'you-cant-recover' => 'Du kannst den Inhalt nicht wiederherstellen.',
    'once-deleted' => 'einmal gelöscht.',
    'delete-files' => 'Dateien löschen',
    'are-you-sure' => 'Bist du dir sicher, dass du dies löschen möchtest?',
    'this-is-permanent-action' => 'Dies ist eine permanente Aktion und die Dateien können nicht wiederhergestellt werden.',
    'name' => 'Name',
    'Größe' => 'Größe',
    'Datum' => 'Datum',
    'home' => 'home',
    'container' => 'Container',
    'is-empty' => 'Dieses Verzeichnis scheint leer zu sein.',
    'is-limited' => 'Dieses Verzeichnis ist zu groß, um es im Browser anzuzeigen, daher wird die Ausgabe auf die ersten 250 Dateien begrenzt.',
    'are-upload-click-to-view' => 'Dateien werden hochgeladen, klicke zum anzeigen.',
    'cancel-uploads' => 'Uploads abbrechen',
    'cancel' => 'abbrechen',
    'close' => 'schließen',
    'create' => 'erstellen',
    'file-name' => 'Dateiname',
    'file-name-description' => 'Gib den Namen ein, unter dem diese Datei gespeichert werden soll.',
    'directory-will-be-as' => 'Dieses Verzeichnis wird erstellt als',
    'rename-description' => 'Gib den neuen Namen und das neue Verzeichnis dieser Datei oder dieses Ordners ein, relativ zum aktuellen Verzeichnis.',
    'new-location' => 'Neuer Ort',
    'drag-and-drop' => 'Ziehe die Dateien zum Hochladen per Drag and Drop.',

    'folders-not-supported' => 'Folder uploads are not supported at this time.',
    'upload-files' => 'Upload Files',
    'folder-too-big' => 'Folder size exceeds 10MB limit. Please select a smaller folder.',
    'upload-folders' => 'Upload Folders',
    'upload-from-url' => 'Upload from URL',
    'filename' => 'Filename',
    'open-code-editor' => 'Open Code Editor',

    'code-editor' => [
        'explorer' => 'Explorer',
        'reload' => 'Reload',
        'new' => 'New',
        'browse-files' => 'Browse Files',
        'save' => 'Save',
        'save-dirty' => 'Save *',
        'saving' => 'Saving...',
        'no-file-selected' => 'No file selected',
        'no-files-found' => 'No files found',
        'loading' => 'Loading...',

        'file-be-created' => 'This file will be created as',
    ],
    
    'edit' => [
        'youre-editing' => 'Du bearbeitest',
        'will-be-exluded' => 'Alle Dateien oder Verzeichnisse, die hier aufgeführt sind, werden vom Backup ausgeschlossen. Wildcards werden durch die Verwendung eines Sternchens unterstützt',
        'you-can-negate' => 'Du kannst eine vorherige Regel negieren, indem du ein Ausrufezeichen voranstellst',
        'save-content' => 'Inhalt speichern',
        'create-file' => 'Datei erstellen',
    ],
];