<?php

return [
    'support' => 'Support center',

    'login' => [
        'title' => 'Login to Continue',
        'username-or-email' => 'Username or Email',
        'password' => 'Password',
        'forgot-password' => 'Forgot password?',
        'login' => 'Login',

        'must-be-provided' => 'A username or email must be provided.',
        'please-enter-password' => 'Please enter your account password',
    ],

    'forgot' => [
        'title' => 'Request Password Reset',
        'email' => 'Email',
        'email-description' => 'Enter your account email address to receive instructions on resetting your password.',
        'send-email' => 'Send Email',
        'return-to-login' => 'Return to Login',

        'a-valid-email-provided' => 'A valid email address must be provided to continue.',
    ],

    'device' => [
        'title' => 'Device Checkpoint',
        'recovery-code' => 'Recovery Code',
        'authentication-code' => 'Authentication Code',

        'continue' => 'Continue',

        'lost-device' => 'I\'ve Lost My Device',
        'have-device' => 'I Have My Device',

        'return-to-login' => 'Return to Login',

        'enter-one-of-recovery-codes' => 'Enter one of the recovery codes generated when you setup 2-Factor authentication on this account in order to continue.',
        'enter-two-factor' => 'Enter the two-factor token generated by your device',
    ],

    'reset' => [
        'title' => 'Reset Password',

        'email' => 'Email',
        'password' => 'Password',
        'confirm-password' => 'Confirm New Password',

        'return-to-login' => 'Return to Login',
        
        'password-required' => 'A new password is required.',
        'at-least-8-characters' => 'Your new password should be at least 8 characters in length.',
        'password-does-not-match' => 'Your new password does not match.',
    ]
];