<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Uruchamianie',
    'stopping' => 'Zatrzymywanie',
    'suspended' => 'Zawieszony',
    'connection-error' => 'Błąd połączenia',
    'transferring' => 'Transferowanie',
    'installing' => 'Instalowanie',
    'restoring-backup' => 'Przywracanie z kopii zapasowej',
    'unavailable' => 'Niedostępny',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Pamięć',
    'disk' => 'Dysk',
    'unlimited' => 'Nieograniczony',
    'start' => 'Uruchom',
    'restart' => 'Restartuj',
    'stop' => 'Zatrzymaj',
    'kill' => 'Zabij',
    'forcibly-stop-process' => 'Wymuś zatrzymanie procesu',
    'continue' => 'Kontynuuj',
    'forcibly-stopping-alert' => 'Wymuszone zatrzymanie serwera może prowadzić do uszkodzenia danych.',
    'cpu-usage' => 'Użycie CPU',
    'memory-usage' => 'Użycie pamięci',
    'disk-usage' => 'Użycie dysku',
    'inbound-outbound' => 'Przychodzące / Wychodzące',
    'low-resources' => 'Mało zasobów',
    'low-resources-desc' => 'Twój serwer ma mało zasobów, upewnij się, że uaktualniasz swój plan',
    'upgrade-server' => 'Uaktualnij serwer',
    'cancel' => 'Anuluj',
    'copied-text' => 'Skopiowano {{text}} do schowka.',
    'showing' => 'Pokazuje',
    'to' => 'do',
    'of' => 'z',
    'results' => 'wyników.',
];
