<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Opstarten',
    'stopping' => 'Stoppen',
    'suspended' => 'Opgeschort',
    'connection-error' => 'Verbindingsfout',
    'transferring' => 'Overdracht',
    'installing' => 'Installeren',
    'restoring-backup' => 'Back-up herstellen',
    'unavailable' => 'Niet beschikbaar',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Geheugen',
    'disk' => 'Schijf',
    'unlimited' => 'Onbeperkt',
    'start' => 'Start',
    'restart' => 'Herstart',
    'stop' => 'Stop',
    'kill' => 'Stoppen',
    'forcibly-stop-process' => 'Proces gedwongen stoppen',
    'continue' => 'Doorgaan',
    'forcibly-stopping-alert' => 'Het gedwongen stoppen van een server kan leiden tot gegevenscorruptie.',
    'cpu-usage' => 'CPU-gebruik',
    'memory-usage' => 'Geheugengebruik',
    'disk-usage' => 'Schijfgebruik',
    'inbound-outbound' => 'Inkomend / Uitgaand',
    'low-resources' => 'Weinig middelen',
    'low-resources-desc' => 'Uw server heeft te weinig middelen. Zorg ervoor dat u uw plan upgrade.',
    'upgrade-server' => 'Upgrade server',
    'cancel' => 'Annuleren',
    'copied-text' => '{{text}} naar klembord gekopieerd.',
    'showing' => 'Weergeven',
    'to' => 'naar',
    'of' => 'van',
    'results' => 'resultaten.',
];