<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Starting',
    'stopping' => 'Stopping',
    'suspended' => 'Suspended',
    'connection-error' => 'Connection Error',
    'transferring' => 'Transferring',
    'installing' => 'Installing',
    'restoring-backup' => 'Restoring Backup',
    'unavailable' => 'Unavailable',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Memory',
    'disk' => 'Disk',
    'unlimited' => 'Unlimited',
    'start' => 'Start',
    'restart' => 'Restart',
    'stop' => 'Stop',
    'kill' => 'Kill',
    'forcibly-stop-process' => 'Forcibly Stop Process',
    'continue' => 'Continue',
    'forcibly-stopping-alert' => 'Forcibly stopping a server can lead to data corruption.',
    'cpu-usage' => 'CPU Usage',
    'memory-usage' => 'Memory Usage',
    'disk-usage' => 'Disk Usage',
    'inbound-outbound' => 'Inbound / Outbound',
    'low-resources' => 'Low on resources',
    'low-resources-desc' => 'Your server is running low on resources, make sure to upgrade your plan',
    'upgrade-server' => 'Upgrade Server',
    'cancel' => 'Cancel',
    'copied-text' => 'Copied {{text}} to clipboard.',
    'showing' => 'Showing',
    'to' => 'to',
    'of' => 'of',
    'results' => 'results.',
];