<?php

return [
    'online' => 'ਆਨਲਾਈਨ',
    'offline' => 'ਆਫਲਾਈਨ',
    'starting' => 'ਸ਼ੁਰੂ ਹੋ ਰਿਹਾ ਹੈ',
    'stopping' => 'ਰੁਕ ਰਿਹਾ ਹੈ',
    'suspended' => 'ਸਸਪੈਂਡ',
    'connection-error' => 'ਕੁਨੈਕਸ਼ਨ ਗਲਤੀ',
    'transferring' => 'ਟ੍ਰਾਂਸਫਰ ਹੋ ਰਿਹਾ ਹੈ',
    'installing' => 'ਇੰਸਟਾਲ ਕਰ ਰਿਹਾ ਹੈ',
    'restoring-backup' => 'ਬੈਕਅੱਪ ਮੁੜ-ਸਥਾਪਿਤ ਕਰ ਰਿਹਾ ਹੈ',
    'unavailable' => 'ਅਨੁਪਲਬਧ',
    'status' => 'ਹਾਲਤ',
    'CPU' => 'CPU',
    'memory' => 'ਮੈਮਰੀ',
    'disk' => 'ਡਿਸਕ',
    'unlimited' => 'ਅਸੀਮਤ',
    'start' => 'ਸ਼ੁਰੂ',
    'restart' => 'ਮੁੜ-ਸ਼ੁਰੂ',
    'stop' => 'ਰੁਕੋ',
    'kill' => 'ਮਾਰੋ',
    'forcibly-stop-process' => 'ਬਲਜ਼ਰੂਰੀ ਤੌਰ ਤੇ ਪ੍ਰਕ੍ਰਿਯਾ ਰੁਕੋ',
    'continue' => 'ਜਾਰੀ ਰੱਖੋ',
    'forcibly-stopping-alert' => 'ਸਰਵਰ ਨੂੰ ਬਲਜ਼ਰੂਰੀ ਤੌਰ ਤੋਂ ਰੁਕਣ ਦਾ ਅਸਰ ਡਾਟਾ ਭ੍ਰਸ਼ਟਾਚਾਰ ਦੇ ਰਾਹੀਂ ਹੋ ਸਕਦਾ ਹੈ।',
    'cpu-usage' => 'CPU ਵਰਤੋਂ',
    'memory-usage' => 'ਮੈਮਰੀ ਵਰਤੋਂ',
    'disk-usage' => 'ਡਿਸਕ ਵਰਤੋਂ',
    'inbound-outbound' => 'ਆਂਤਰ-ਬਾਹਰ',
    'low-resources' => 'ਸੰਸਾਧਨਾਂ ਤੇ ਘੱਟੋ-ਘੱਟ',
    'low-resources-desc' => 'ਤੁਹਾਡਾ ਸਰਵਰ ਸੰਸਾਧਨਾਂ ਤੇ ਘੱਟੋ-ਘੱਟ ਚੱਲ ਰਿਹਾ ਹੈ, ਕਿਰਪਾ ਕਰਕੇ ਆਪਣੇ ਪਲਾਨ ਨੂੰ ਅੱਪਗਰੇਡ ਕਰੋ',
    'upgrade-server' => 'ਸਰਵਰ ਅੱਪਗਰੇਡ ਕਰੋ',
    'cancel' => 'ਰੱਦ ਕਰੋ',
    'copied-text' => '{{text}} ਨੂੰ ਕਲਿੱਪਬੋਰਡ ਵਿੱਚ ਨਕਲ ਕੀਤਾ ਗਿਆ।',
    'showing' => 'ਦਿਖਾਈ ਜਾ ਰਹੇ ਹਨ',
    'to' => 'ਤੋਂ',
    'of' => 'ਦੀ',
    'results' => 'ਨਤੀਜੇ।',
];
