<?php

return [
    'file-manager' => 'Gerenciador de Arquivos',
    'search' => 'Pesquisar',
    'delete' => 'Excluir',
    'move' => 'Mover',
    'archive' => 'Arquivar',
    'unarchive' => 'Desarquivar',
    'create-directory' => 'Criar Diretório',
    'upload' => 'Fazer Upload',
    'new-file' => 'Novo arquivo',
    'rename' => 'Renomear',
    'permissions' => 'Permissões',
    'copy' => 'Copiar',
    'download' => 'Baixar',
    'update' => 'Atualizar',
    'file-mode' => 'Modo de Arquivo',
    'you-cant-recover' => 'Você não poderá recuperar o conteúdo de',
    'once-deleted' => 'uma vez excluído.',
    'delete-files' => 'Excluir Arquivos',
    'are-you-sure' => 'Você tem certeza que quer excluir',
    'this-is-permanent-action' => 'Esta é uma ação permanente e os arquivos não podem ser recuperados.',
    'name' => 'nome',
    'size' => 'tamanho',
    'date' => 'data',
    'home' => 'início',
    'container' => 'contêiner',
    'is-empty' => 'Este diretório parece estar vazio.',
    'is-limited' => 'Este diretório é grande demais para ser exibido no navegador, limitando a saída para os primeiros 250 arquivos.',
    'are-upload-click-to-view' => 'arquivos estão sendo carregados, clique para visualizar',
    'cancel-uploads' => 'Cancelar Uploads',
    'cancel' => 'Cancelar',
    'close' => 'Fechar',
    'create' => 'Criar',
    'file-name' => 'Nome do Arquivo',
    'file-name-description' => 'Insira o nome com o qual este arquivo deve ser salvo.',
    'directory-will-be-as' => 'Este diretório será criado como',
    'rename-description' => 'Insira o novo nome e diretório deste arquivo ou pasta, relativo ao diretório atual.',
    'new-location' => 'Nova localização',
    'drag-and-drop' => 'Arraste e solte arquivos para fazer upload.',

    'edit' => [
        'youre-editing' => 'Você está editando um',
        'will-be-exluded' => 'arquivo. Quaisquer arquivos ou diretórios listados aqui serão excluídos dos backups. Curingas são suportados usando um asterisco',
        'you-can-negate' => 'Você pode negar uma regra anterior prefixando com um ponto de exclamação',
        'save-content' => 'Salvar Conteúdo',
        'create-file' => 'Criar Arquivo',
    ],
];
