<?php

return [
    'file-manager' => 'Filer',
    'search' => 'Søg',
    'delete' => 'Slet',
    'move' => 'Flyt',
    'archive' => 'Arkiv',
    'unarchive' => 'Udpak',
    'create-directory' => 'Opret Mappe',
    'upload' => 'Upload',
    'new-file' => 'Ny fil',
    'rename' => 'Omdøb',
    'permissions' => 'Tilladelser',
    'copy' => 'Kopiér',
    'download' => 'Download',
    'update' => 'Opdater',
    'file-mode' => 'Filtilstand',
    'you-cant-recover' => 'Du vil ikke kunne gendanne indholdet af',
    'once-deleted' => 'når det er slettet.',
    'delete-files' => 'Slet Filer',
    'are-you-sure' => 'Er du sikker på, at du vil slette',
    'this-is-permanent-action' => 'Dette er en permanent handling, og filerne kan ikke gendannes.',
    'name' => 'Navn',
    'size' => 'Størrelse',
    'date' => 'Dato',
    'home' => 'Hjem',
    'container' => 'Beholder',
    'is-empty' => 'Denne mappe ser ud til at være tom.',
    'is-limited' => 'Denne mappe er for stor til at vise i browseren. Outputtet begrænses til de første 250 filer.',
    'are-upload-click-to-view' => 'filer uploades, klik for at se',
    'cancel-uploads' => 'Annuller Uploads',
    'cancel' => 'Annuller',
    'close' => 'Luk',
    'create' => 'Opret',
    'file-name' => 'Filnavn',
    'file-name-description' => 'Indtast det navn, som denne fil skal gemmes som.',
    'directory-will-be-as' => 'Denne mappe oprettes som',
    'rename-description' => 'Indtast det nye navn og den nye placering for denne fil eller mappe i forhold til den aktuelle mappe.',
    'new-location' => 'Ny placering',
    'drag-and-drop' => 'Træk og slip filer for at uploade.',

    'edit' => [
        'youre-editing' => 'Du redigerer en',
        'will-be-exluded' => 'fil. Eventuelle filer eller mapper nævnt her vil blive udeladt fra sikkerhedskopier. Wildcards understøttes ved at bruge en asterisk',
        'you-can-negate' => 'Du kan negere en tidligere regel ved at tilføje et udråbstegn foran.',
        'save-content' => 'Gem Indhold',
        'create-file' => 'Opret Fil',
    ],
];