<?php 

return [
    'schedules' => 'Planlægninger',
    'manage-schedules' => 'Administrer planlægninger',
    'create-schedule' => 'Opret planlægning',
    'name' => 'Navn',
    'last-run-at' => 'Sidst kørt kl.',
    'next-run-at' => 'Næste kørsel kl.',
    'status' => 'Status',
    'active' => 'Aktiv',
    'inactive' => 'Inaktiv',
    'processing' => 'Behandler',
    'manage-schedule' => 'Administrer planlægning',
    'new-task' => 'Ny opgave',
    'run-now' => 'Kør nu',
    'editBtn' => 'Rediger',
    'n/a' => 'Ukendt',
    'never' => 'Aldrig',

    'no-schedules' => 'Der er ingen planlægninger konfigureret for denne server.',
    'ignore-files-folders' => 'Ignorer filer og mapper',
    'continues-on-failure' => 'Fortsæt ved fejl',
    'later' => 'senere',

    'minute' => 'Minut',
    'hour' => 'Time',
    'day' => 'Dag',
    'week' => 'Uge',
    'day-of-month' => 'Dag i måned',
    'month' => 'Måned',
    'day-of-week' => 'Dag i ugen',

    'deleteTask' => [
        'title' => 'Bekræft sletning af opgave',
        'description' => 'Er du sikker på, at du vil slette denne opgave? Denne handling kan ikke gøres om.',
        'delete' => 'Slet opgave'
    ],
    'delete' => [
        'title' => 'Slet planlægning',
        'description' => 'Alle opgaver fjernes, og eventuelle kørende processer afsluttes.',
        'delete' => 'Slet'
    ],
    'edit' => [
        'title-1' => 'Rediger planlægning',
        'title-2' => 'Opret ny planlægning',

        'description' => 'Planlægningssystemet understøtter brugen af Cronjob-syntaks til at definere, hvornår opgaver skal begynde at køre. Brug felterne ovenfor til at specificere, hvornår disse opgaver skal begynde at køre.',
        
        'name' => 'Planlægningsnavn',
        'name-description' => 'En menneskelig læsbar identifikator for denne planlægning.',
        'cheatsheet' => 'Vis hjælpeside',
        'cheatsheet-description' => 'Vis cron-hjælpesiden med nogle eksempler',
        'online-when-online' => 'Kun når serveren er online',
        'online-when-online-description' => 'Udfør kun denne planlægning, når serveren kører.',
        'enabled' => 'Planlægning aktiveret',
        'enabled-description' => 'Denne planlægning udføres automatisk, hvis den er aktiveret.',

        'save-changes' => 'Gem ændringer',
    ],
    'cheatsheet' => [
        'example' => 'Eksempler',
        'every-5-minutes' => 'hver 5. minut',
        'every-hour' => 'hver time',
        'hour-range' => 'timeområde',
        'once-a-day' => 'en gang om dagen',
        'every-monday' => 'hver mandag',
        'special-characters' => 'Særlige tegn',
        'any-value' => 'hvilken som helst værdi',
        'value-list-separator' => 'værdiliste-separator',
        'range-values' => 'intervalværdier',
        'step-values' => 'trinværdier',
    ],
    'task' => [
        'message' => 'En sikkerhedskopieringsopgave kan ikke oprettes, når grænsen for serverens sikkerhedskopier er sat til 0.',
        'edit-task' => 'Rediger opgave',
        'save-changes' => 'Gem ændringer',
        'create-task' => 'Opret opgave',
        'action' => 'Handling',
        'send-command' => 'Send kommando',
        'send-power-action' => 'Send strømhandling',
        'create-backup' => 'Opret sikkerhedskopi',
        'offset' => 'Tidsforskydning (i sekunder)',
        'offset-description' => 'Tiden, der skal vente, efter at den forrige opgave er udført, før denne startes. Hvis dette er den første opgave på en plan, anvendes dette ikke.',
        'payload' => 'Nyttelast',
        'ignored-files' => 'Ignorerede filer',
        'ignored-files-description' => 'Valgfrit. Indeholder de filer og mapper, der skal udelukkes fra denne sikkerhedskopi. Som standard bruges indholdet af din .pteroignore-fil. Hvis du har nået din grænse for sikkerhedskopier, roteres den ældste sikkerhedskopi.',
        'start-server' => 'Start serveren',
        'stop-server' => 'Stop serveren',
        'restart-server' => 'Genstart serveren',
        'kill-server' => 'Dræb serveren',
        'continue-on-failure' => 'Fortsæt ved fejl',
        'continue-on-failure-description' => 'Fremtidige opgaver køres, når denne opgave mislykkes.',
    ],
];
