<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Start ho raha hai',
    'stopping' => 'Band ho raha hai',
    'suspended' => 'Suspended',
    'connection-error' => 'Connection error',
    'transferring' => 'Transfer ho raha hai',
    'installing' => 'Install ho raha hai',
    'restoring-backup' => 'Backup restore ho raha hai',
    'unavailable' => 'Available nahi',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Memory',
    'disk' => 'Disk',
    'unlimited' => 'Unlimited',
    'start' => 'Start',
    'restart' => 'Restart',
    'stop' => 'Stop',
    'kill' => 'Force stop',
    'forcibly-stop-process' => 'Process ko force se roko',
    'continue' => 'Continue',
    'forcibly-stopping-alert' => 'Server ko force se stop karna data corruption ka reason ban sakta hai.',
    'cpu-usage' => 'CPU usage',
    'memory-usage' => 'Memory usage',
    'disk-usage' => 'Disk usage',
    'inbound-outbound' => 'Inbound / outbound',
    'low-resources' => 'Resources kam hain',
    'low-resources-desc' => 'Aapka server resources par kam chal raha hai, yeh serious ho sakta hai, please apna plan upgrade karo.',
    'upgrade-server' => 'Server upgrade karo',
    'cancel' => 'Cancel',
    'copied-text' => '{{text}} clipboard par copy ho gaya.',
    'showing' => 'Showing',
    'to' => 'se',
    'of' => 'mein se',
    'results' => 'results.',
];
