<?php

return [
    'file-manager' => 'ファイルマネージャー',
    'search' => '検索',
    'delete' => '削除',
    'move' => '移動',
    'archive' => 'アーカイブ',
    'unarchive' => 'アーカイブ解除',
    'create-directory' => 'ディレクトリを作成',
    'upload' => 'アップロード',
    'new-file' => '新しいファイル',
    'rename' => '名前を変更',
    'permissions' => '権限',
    'copy' => 'コピー',
    'download' => 'ダウンロード',
    'update' => '更新',

    'file-mode' => 'ファイルモード',
    'you-cant-recover' => 'の内容を回復することはできません',
    'once-deleted' => '（削除後）。',
    'delete-files' => 'ファイルを削除',
    'are-you-sure' => '削除してもよろしいですか',
    'this-is-permanent-action' => 'これは永続的な操作であり、ファイルは回復できません。',
    'name' => '名前',
    'size' => 'サイズ',
    'date' => '日付',
    'home' => 'ホーム',
    'container' => 'コンテナ',
    'is-empty' => 'このディレクトリは空のようです。',
    'is-limited' => 'このディレクトリはブラウザに表示するには大きすぎるため、最初の250ファイルに制限されています。',
    'are-upload-click-to-view' => 'ファイルをアップロード中、クリックして確認',
    'cancel-uploads' => 'アップロードをキャンセル',
    'cancel' => 'キャンセル',
    'close' => '閉じる',
    'create' => '作成',
    'file-name' => 'ファイル名',
    'file-name-description' => 'このファイルの保存名を入力してください。',
    'directory-will-be-as' => 'このディレクトリは次のように作成されます',
    'rename-description' => '現在のディレクトリからの相対パスで、このファイルまたはフォルダの新しい名前とディレクトリを入力してください。',
    'new-location' => '新しい場所',
    'drag-and-drop' => 'ファイルをドラッグ＆ドロップしてアップロード。',

    'folders-not-supported' => 'フォルダのアップロードは現在サポートされていません。',
    'upload-files' => 'ファイルをアップロード',
    'folder-too-big' => 'フォルダサイズが10MBの制限を超えています。より小さいフォルダを選択してください。',
    'upload-folders' => 'フォルダをアップロード',
    'upload-from-url' => 'URLからアップロード',
    'filename' => 'ファイル名',
    'open-code-editor' => 'コードエディタを開く',

    'code-editor' => [
        'explorer' => 'エクスプローラー',
        'reload' => '再読み込み',
        'new' => '新規',
        'browse-files' => 'ファイルを参照',
        'save' => '保存',
        'save-dirty' => '保存 *',
        'saving' => '保存中...',
        'no-file-selected' => 'ファイルが選択されていません',
        'no-files-found' => 'ファイルが見つかりません',
        'loading' => '読み込み中...',

        'file-be-created' => 'このファイルは次のように作成されます',
    ],
    
    'edit' => [
        'youre-editing' => '編集中のファイルは',
        'will-be-exluded' => 'ファイルです。ここにリストされているファイルやディレクトリはバックアップから除外されます。ワイルドカードにはアスタリスクを使用できます',
        'you-can-negate' => '感嘆符を頭に付けることで以前のルールを否定できます',
        'save-content' => 'コンテンツを保存',
        'create-file' => 'ファイルを作成',
    ],
];