<?php 

return [
    'schedules' => 'スケジュール',
    'manage-schedules' => 'スケジュールを管理',
    'create-schedule' => 'スケジュールを作成',
    'name' => '名前',
    'last-run-at' => '最後の実行',
    'next-run-at' => '次の実行',
    'status' => 'ステータス',
    'active' => 'アクティブ',
    'inactive' => '非アクティブ',
    'processing' => '処理中',
    'manage-schedule' => 'スケジュールを管理',
    'new-task' => '新しいタスク',
    'run-now' => '今すぐ実行',
    'editBtn' => '編集',
    'n/a' => 'N/A',
    'never' => 'なし',

    'no-schedules' => 'このサーバーにはスケジュールが設定されていません。',
    'ignore-files-folders' => 'ファイルとフォルダを無視',
    'continues-on-failure' => '失敗時に続行',
    'later' => '後で',

    'minute' => '分',
    'hour' => '時',
    'day' => '日',
    'week' => '週',
    'day-of-month' => '月の日',
    'month' => '月',
    'day-of-week' => '曜日',

    'deleteTask' => [
        'title' => 'タスクの削除を確認',
        'description' => 'このタスクを削除してもよろしいですか？この操作は元に戻せません。',
        'delete' => 'タスクを削除'
    ],
    'delete' => [
        'title' => 'スケジュールを削除',
        'description' => 'すべてのタスクが削除され、実行中のプロセスはすべて終了します。',
        'delete' => '削除'
    ],
    'edit' => [
        'title-1' => 'スケジュールを編集',
        'title-2' => '新しいスケジュールを作成',

        'description' => 'スケジュールシステムはタスクの開始時刻を定義する際にCronジョブ構文の使用をサポートしています。上のフィールドを使用してタスクを開始する時刻を指定してください。',
        
        'name' => 'スケジュール名',
        'name-description' => 'このスケジュールの人が読める識別子。',
        'cheatsheet' => 'チートシートを表示',
        'cheatsheet-description' => 'Cronチートシートで例を確認',
        'online-when-online' => 'サーバーがオンライン時のみ',
        'online-when-online-description' => 'サーバーが実行中の状態にある場合にのみこのスケジュールを実行します。',
        'enabled' => 'スケジュール有効',
        'enabled-description' => '有効の場合、このスケジュールは自動的に実行されます。',

        'easy-mode' => 'かんたんモード',
        'easy-mode-description' => 'カスタムCron設定については詳細モードに切り替え',
        'easy' => 'かんたん',
        'advanced' => '詳細',

        'save-changes' => '変更を保存',
    ],
    'cheatsheet' => [
        'example' => '例',
        'every-5-minutes' => '5分ごと',
        'every-hour' => '毎時',
        'hour-range' => '時間範囲',
        'once-a-day' => '1日1回',
        'every-monday' => '毎週月曜日',
        'special-characters' => '特殊文字',
        'any-value' => '任意の値',
        'value-list-separator' => '値リスト区切り文字',
        'range-values' => '範囲値',
        'step-values' => 'ステップ値',
    ],
    'task' => [
        'message' => 'サーバーのバックアップ上限が0に設定されている場合、バックアップタスクを作成できません。',
        'edit-task' => 'タスクを編集',
        'easy-mode' => 'かんたんモード',
        'easy-mode-description' => 'カスタムCron設定については詳細モードに切り替え',
        'easy' => 'かんたん',
        'advanced' => '詳細',

        'save-changes' => '変更を保存',
        'create-task' => 'タスクを作成',
        'action' => 'アクション',
        'send-command' => 'コマンドを送信',
        'send-power-action' => '電源アクションを送信',
        'create-backup' => 'バックアップを作成',
        'offset' => 'タイムオフセット（秒）',
        'offset-description' => '前のタスクが実行された後、このタスクを実行するまでの待機時間。スケジュールの最初のタスクの場合は適用されません。',
        'payload' => 'ペイロード',
        'ignored-files' => '無視するファイル',
        'ignored-files-description' => 'オプション。このバックアップで除外するファイルとフォルダを含めます。デフォルトでは.pteroignoreファイルの内容が使用されます。バックアップ上限に達した場合、最も古いバックアップが削除されます。',
        'start-server' => 'サーバーを起動',
        'stop-server' => 'サーバーを停止',
        'restart-server' => 'サーバーを再起動',
        'kill-server' => 'サーバーを強制終了',
        'continue-on-failure' => '失敗時に続行',
        'continue-on-failure-description' => 'このタスクが失敗した場合、以降のタスクが実行されます。',
    ],
];