<?php

return [
    'file-manager' => 'Gerenciador de Arquivos',
    'search' => 'Buscar',
    'delete' => 'Excluir',
    'move' => 'Mover',
    'archive' => 'Arquivar',
    'unarchive' => 'Desarquivar',
    'create-directory' => 'Criar Diretório',
    'upload' => 'Enviar',
    'new-file' => 'Novo arquivo',
    'rename' => 'Renomear',
    'permissions' => 'Permissões',
    'copy' => 'Copiar',
    'download' => 'Download',
    'update' => 'Atualizar',
    'file-mode' => 'Modo do Arquivo',
    'you-cant-recover' => 'Você não poderá recuperar o conteúdo de',
    'once-deleted' => 'uma vez excluído.',
    'delete-files' => 'Excluir Arquivos',
    'are-you-sure' => 'Tem certeza de que deseja excluir',
    'this-is-permanent-action' => 'Esta é uma ação permanente e os arquivos não podem ser recuperados.',
    'name' => 'nome',
    'size' => 'tamanho',
    'date' => 'data',
    'home' => 'início',
    'container' => 'contêiner',
    'is-empty' => 'Este diretório parece estar vazio.',
    'is-limited' => 'Este diretório é muito grande para ser exibido no navegador, limitando a saída aos primeiros 250 arquivos.',
    'are-upload-click-to-view' => 'arquivos estão sendo enviados, clique para visualizar',
    'cancel-uploads' => 'Cancelar Envios',
    'cancel' => 'Cancelar',
    'close' => 'Fechar',
    'create' => 'Criar',
    'file-name' => 'Nome do Arquivo',
    'file-name-description' => 'Digite o nome que este arquivo deve ter.',
    'directory-will-be-as' => 'Este diretório será criado como',
    'rename-description' => 'Digite o novo nome e diretório deste arquivo ou pasta, em relação ao diretório atual.',
    'new-location' => 'Nova Localização',
    'drag-and-drop' => 'Arraste e solte arquivos para enviar.',

    'edit' => [
        'youre-editing' => 'Você está editando um',
        'will-be-exluded' => 'arquivo. Quaisquer arquivos ou diretórios listados aqui serão excluídos dos backups. Wildcards são suportados usando um asterisco',
        'you-can-negate' => 'Você pode negar uma regra anterior prefixando um ponto de exclamação',
        'save-content' => 'Salvar Conteúdo',
        'create-file' => 'Criar Arquivo',
    ],
];
