<?php

return [
    'file-manager' => 'Bestandsbeheer',
    'search' => 'Zoeken',
    'delete' => 'Verwijderen',
    'move' => 'Verplaatsen',
    'archive' => 'Archiveren',
    'unarchive' => 'Dearchiveren',
    'create-directory' => 'Map aanmaken',
    'upload' => 'Uploaden',
    'new-file' => 'Nieuw bestand',
    'rename' => 'Hernoemen',
    'permissions' => 'Machtigingen',
    'copy' => 'Kopiëren',
    'download' => 'Downloaden',
    'update' => 'Bijwerken',

    'file-mode' => 'Bestandsmodus',
    'you-cant-recover' => 'U kunt de inhoud van niet herstellen',
    'once-deleted' => 'nadat het is verwijderd.',
    'delete-files' => 'Bestanden verwijderen',
    'are-you-sure' => 'Weet u zeker dat u wilt verwijderen',
    'this-is-permanent-action' => 'Dit is een permanente actie en de bestanden kunnen niet worden hersteld.',
    'name' => 'naam',
    'size' => 'grootte',
    'date' => 'datum',
    'home' => 'thuis',
    'container' => 'container',
    'is-empty' => 'Deze map lijkt leeg te zijn.',
    'is-limited' => 'Deze map is te groot om in de browser weer te geven; de uitvoer is beperkt tot de eerste 250 bestanden.',
    'are-upload-click-to-view' => 'bestanden worden geüpload, klik om te bekijken',
    'cancel-uploads' => 'Uploads annuleren',
    'cancel' => 'Annuleren',
    'close' => 'Sluiten',
    'create' => 'Aanmaken',
    'file-name' => 'Bestandsnaam',
    'file-name-description' => 'Voer de naam in waaronder dit bestand moet worden opgeslagen.',
    'directory-will-be-as' => 'Deze map wordt aangemaakt als',
    'rename-description' => 'Voer de nieuwe naam en map van dit bestand of deze map in, relatief aan de huidige map.',
    'new-location' => 'Nieuwe locatie',
    'drag-and-drop' => 'Sleep bestanden om ze te uploaden.',

    'folders-not-supported' => 'Het uploaden van mappen wordt momenteel niet ondersteund.',
    'upload-files' => 'Bestanden uploaden',
    'folder-too-big' => 'Mapgrootte overschrijdt de limiet van 10 MB. Selecteer een kleinere map.',
    'upload-folders' => 'Mappen uploaden',
    'upload-from-url' => 'Uploaden via URL',
    'filename' => 'Bestandsnaam',
    'open-code-editor' => 'Code-editor openen',

    'code-editor' => [
        'explorer' => 'Verkenner',
        'reload' => 'Herladen',
        'new' => 'Nieuw',
        'browse-files' => 'Bestanden bladeren',
        'save' => 'Opslaan',
        'save-dirty' => 'Opslaan *',
        'saving' => 'Opslaan...',
        'no-file-selected' => 'Geen bestand geselecteerd',
        'no-files-found' => 'Geen bestanden gevonden',
        'loading' => 'Laden...',

        'file-be-created' => 'Dit bestand wordt aangemaakt als',
    ],
    
    'edit' => [
        'youre-editing' => 'U bewerkt een',
        'will-be-exluded' => 'bestand. Alle bestanden of mappen die hier worden vermeld, worden uitgesloten van back-ups. Jokertekens worden ondersteund met een asterisk',
        'you-can-negate' => 'U kunt een eerdere regel negeren door een uitroepteken voor te voegen',
        'save-content' => 'Inhoud opslaan',
        'create-file' => 'Bestand aanmaken',
    ],
];