<?php 

return [
    'schedules' => 'Schema\'s',
    'manage-schedules' => 'Schema\'s beheren',
    'create-schedule' => 'Schema aanmaken',
    'name' => 'Naam',
    'last-run-at' => 'Laatst uitgevoerd om',
    'next-run-at' => 'Volgende uitvoering om',
    'status' => 'Status',
    'active' => 'Actief',
    'inactive' => 'Inactief',
    'processing' => 'Verwerken',
    'manage-schedule' => 'Schema beheren',
    'new-task' => 'Nieuwe taak',
    'run-now' => 'Nu uitvoeren',
    'editBtn' => 'Bewerken',
    'n/a' => 'n.v.t.',
    'never' => 'nooit',

    'no-schedules' => 'Er zijn geen schema\'s geconfigureerd voor deze server.',
    'ignore-files-folders' => 'Bestanden en mappen negeren',
    'continues-on-failure' => 'Gaat door bij mislukking',
    'later' => 'later',

    'minute' => 'Minuut',
    'hour' => 'Uur',
    'day' => 'Dag',
    'week' => 'Week',
    'day-of-month' => 'Dag van de maand',
    'month' => 'Maand',
    'day-of-week' => 'Dag van de week',

    'deleteTask' => [
        'title' => 'Taakverwijdering bevestigen',
        'description' => 'Weet je zeker dat je deze taak wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.',
        'delete' => 'Taak verwijderen'
    ],
    'delete' => [
        'title' => 'Schema verwijderen',
        'description' => 'Alle taken worden verwijderd en alle lopende processen worden beëindigd.',
        'delete' => 'Verwijderen'
    ],
    'edit' => [
        'title-1' => 'Schema bewerken',
        'title-2' => 'Nieuw schema aanmaken',

        'description' => 'Het schemasysteem ondersteunt het gebruik van Cronjob-syntaxis bij het definiëren wanneer taken moeten beginnen. Gebruik de bovenstaande velden om te specificeren wanneer deze taken moeten beginnen.',
        
        'name' => 'Schemanaam',
        'name-description' => 'Een voor mensen leesbare identificator voor dit schema.',
        'cheatsheet' => 'Spiekbriefje weergeven',
        'cheatsheet-description' => 'Toon het cron-spiekbriefje voor voorbeelden',
        'online-when-online' => 'Alleen wanneer de server online is',
        'online-when-online-description' => 'Voer dit schema alleen uit wanneer de server actief is.',
        'enabled' => 'Schema ingeschakeld',
        'enabled-description' => 'Dit schema wordt automatisch uitgevoerd indien ingeschakeld.',

        'easy-mode' => 'Eenvoudige modus',
        'easy-mode-description' => 'Schakel over naar geavanceerde modus voor aangepaste cron-configuratie',
        'easy' => 'Eenvoudig',
        'advanced' => 'Geavanceerd',

        'save-changes' => 'Wijzigingen opslaan',
    ],
    'cheatsheet' => [
        'example' => 'Voorbeelden',
        'every-5-minutes' => 'elke 5 minuten',
        'every-hour' => 'elk uur',
        'hour-range' => 'uurreeks',
        'once-a-day' => 'eenmaal per dag',
        'every-monday' => 'elke maandag',
        'special-characters' => 'Speciale tekens',
        'any-value' => 'elke waarde',
        'value-list-separator' => 'lijstscheidingsteken',
        'range-values' => 'reekswaarden',
        'step-values' => 'stapgrootte',
    ],
    'task' => [
        'message' => 'Een back-uptaak kan niet worden aangemaakt als de back-uplimiet van de server is ingesteld op 0.',
        'edit-task' => 'Taak bewerken',
        'easy-mode' => 'Eenvoudige modus',
        'easy-mode-description' => 'Schakel over naar geavanceerde modus voor aangepaste cron-configuratie',
        'easy' => 'Eenvoudig',
        'advanced' => 'Geavanceerd',

        'save-changes' => 'Wijzigingen opslaan',
        'create-task' => 'Taak aanmaken',
        'action' => 'Actie',
        'send-command' => 'Opdracht verzenden',
        'send-power-action' => 'Energieactie verzenden',
        'create-backup' => 'Back-up aanmaken',
        'offset' => 'Tijdsvertraging (in seconden)',
        'offset-description' => 'De wachttijd na het uitvoeren van de vorige taak voordat deze wordt uitgevoerd. Als dit de eerste taak in een schema is, wordt dit niet toegepast.',
        'payload' => 'Payload',
        'ignored-files' => 'Genegeerde bestanden',
        'ignored-files-description' => 'Optioneel. Voeg de bestanden en mappen toe die moeten worden uitgesloten van deze back-up. Standaard wordt de inhoud van je.pteroignore-bestand gebruikt. Als je jeback-uplimiet heeft bereikt, wordt de oudste back-up verwijderd.',
        'start-server' => 'Server starten',
        'stop-server' => 'Server stoppen',
        'restart-server' => 'Server herstarten',
        'kill-server' => 'Server beëindigen',
        'continue-on-failure' => 'Doorgaan bij mislukking',
        'continue-on-failure-description' => 'Toekomstige taken worden uitgevoerd wanneer deze taak mislukt.',
    ],
];