<?php 

return [
    'schedules' => 'Schedules',
    'manage-schedules' => 'Manage schedules',
    'create-schedule' => 'Create schedule',
    'name' => 'Name',
    'last-run-at' => 'Last run at',
    'next-run-at' => 'Next run at',
    'status' => 'Status',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'processing' => 'Processing',
    'manage-schedule' => 'Manage schedule',
    'new-task' => 'New Task',
    'run-now' => 'Run Now',
    'editBtn' => 'Edit',
    'n/a' => 'n/a',
    'never' => 'never',

    'no-schedules' => 'There are no schedules configured for this server.',
    'ignore-files-folders' => 'Ignoring files & folders',
    'continues-on-failure' => 'Continues on Failure',
    'later' => 'later',

    'minute' => 'Minute',
    'hour' => 'Hour',
    'day' => 'Day',
    'week' => 'Week',
    'day-of-month' => 'Day of month',
    'month' => 'Month',
    'day-of-week' => 'Day of week',

    'deleteTask' => [
        'title' => 'Confirm task deletion',
        'description' => 'Are you sure you want to delete this task? This action cannot be undone.',
        'delete' => 'Delete Task'
    ],
    'delete' => [
        'title' => 'Delete Schedule',
        'description' => 'All tasks will be removed and any running processes will be terminated.',
        'delete' => 'Delete'
    ],
    'edit' => [
        'title-1' => 'Edit schedule',
        'title-2' => 'Create new schedule',

        'description' => 'The schedule system supports the use of Cronjob syntax when defining when tasks should begin running. Use the fields above to specify when these tasks should begin running.',
        
        'name' => 'Schedule name',
        'name-description' => 'A human readable identifier for this schedule.',
        'cheatsheet' => 'Show Cheatsheet',
        'cheatsheet-description' => 'Show the cron cheatsheet for some examples',
        'online-when-online' => 'Only When Server Is Online',
        'online-when-online-description' => 'Only execute this schedule when the server is in a running state.',
        'enabled' => 'Schedule Enabled',
        'enabled-description' => 'This schedule will be executed automatically if enabled.',

        'save-changes' => 'Save changes',
    ],
    'cheatsheet' => [
        'example' => 'Examples',
        'every-5-minutes' => 'every 5 minutes',
        'every-hour' => 'every hour',
        'hour-range' => 'hour range',
        'once-a-day' => 'once a day',
        'every-monday' => 'every monday',
        'special-characters' => 'Special Characters',
        'any-value' => 'any value',
        'value-list-separator' => 'value list separator',
        'range-values' => 'range values',
        'step-values' => 'step values',
    ],
    'task' => [
        'message' => 'A backup task cannot be created when the server\'s backup limit is set to 0.',
        'edit-task' => 'Edit Task',
        'save-changes' => 'Save Changes',
        'create-task' => 'Create Task',
        'action' => 'Action',
        'send-command' => 'Send command',
        'send-power-action' => 'Send power action',
        'create-backup' => 'Create backup',
        'offset' => 'Time offset (in seconds)',
        'offset-description' => 'The amount of time to wait after the previous task executes before running this one. If this is the first task on a schedule this will not be applied.',
        'payload' => 'Payload',
        'ignored-files' => 'Ignored Files',
        'ignored-files-description' => 'Optional. Include the files and folders to be excluded in this backup. By default, the contents of your .pteroignore file will be used. If you have reached your backup limit, the oldest backup will be rotated.',
        'start-server' => 'Start the server',
        'stop-server' => 'Stop the server',
        'restart-server' => 'Restart the server',
        'kill-server' => 'Terminate the server',
        'continue-on-failure' => 'Continue on Failure',
        'continue-on-failure-description' => 'Future tasks will be run when this task fails.',
    ],
];