<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Starten',
    'stopping' => 'Stoppen',
    'suspended' => 'Opgeschort',
    'connection-error' => 'Verbindingsfout',
    'transferring' => 'Overbrengen',
    'installing' => 'Installeren',
    'restoring-backup' => 'Back-up terugzetten',
    'unavailable' => 'Niet beschikbaar',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Geheugen',
    'disk' => 'Schijf',
    'unlimited' => 'Onbeperkt',
    'start' => 'Starten',
    'restart' => 'Herstarten',
    'stop' => 'Stoppen',
    'kill' => 'Beëindigen',
    'forcibly-stop-process' => 'Proces geforceerd stoppen',
    'continue' => 'Doorgaan',
    'forcibly-stopping-alert' => 'Het geforceerd stoppen van een server kan leiden tot gegevensbeschadiging.',
    'cpu-usage' => 'CPU-gebruik',
    'memory-usage' => 'Geheugengebruik',
    'disk-usage' => 'Schijfgebruik',
    'inbound-outbound' => 'Inkomend / Uitgaand',
    'low-resources' => 'Weinig resources',
    'low-resources-desc' => 'Uw server heeft weinig resources, zorg er voor dat u uw abonnement upgradet',
    'upgrade-server' => 'Server upgraden',
    'cancel' => 'Annuleren',
    'copied-text' => '{{text}} gekopieerd naar klembord.',
    'showing' => 'Weergeven',
    'to' => 'tot',
    'of' => 'van',
    'results' => 'resultaten.',
];