<?php

return [
    'online' => 'Įjungtas',
    'offline' => 'Išjungtas',
    'starting' => 'Paleidžiamas',
    'stopping' => 'Stabdomas',
    'suspended' => 'Pristabdytas',
    'connection-error' => 'Ryšio klaida',
    'transferring' => 'Perkeliamas',
    'installing' => 'Diegiamas',
    'restoring-backup' => 'Atkuriama atsarginė kopija',
    'unavailable' => 'Nepasiekiamas',
    'status' => 'Būsena',
    'CPU' => 'Procesorius',
    'memory' => 'RAM',
    'disk' => 'Disko vieta',
    'unlimited' => 'Neribota',
    'start' => 'Paleisti',
    'restart' => 'Paleisti iš naujo',
    'stop' => 'Stabdyti',
    'kill' => 'Priverstinai sustabdyti',
    'forcibly-stop-process' => 'Priverstinai sustabdyti procesą',
    'continue' => 'Tęsti',
    'forcibly-stopping-alert' => 'Priverstinis serverio stabdymas gali sukelti duomenų sugadinimą.',
    'cpu-usage' => 'Procesoriaus naudojimas',
    'memory-usage' => 'RAM naudojimas',
    'disk-usage' => 'Disko naudojimas',
    'inbound-outbound' => 'Įeinantis / Išeinantis',
    'low-resources' => 'Trūksta resursų',
    'low-resources-desc' => 'Jūsų serveriui trūksta resursų, įsitikinkite, kad atnaujinate savo planą',
    'upgrade-server' => 'Atnaujinti serverį',
    'cancel' => 'Atšaukti',
    'copied-text' => '„{{text}}“ nukopijuota į iškarpinę.',
    'showing' => 'Rodoma',
    'to' => 'iki',
    'of' => 'iš',
    'results' => 'rezultatų.',
];