<?php

return [
    'file-manager' => 'File Manager', 
    'search' => 'Maghanap',
    'delete' => 'Tanggalin',
    'move' => 'Ilipat',
    'archive' => 'I-archive', 
    'unarchive' => 'I-unarchive', 
    'create-directory' => 'Gumawa ng Direktoryo', 
    'upload' => 'Mag-upload', 
    'new-file' => 'Bagong file',
    'rename' => 'Palitan ang pangalan', 
    'permissions' => 'Mga Pahintulot', 
    'copy' => 'Kopyahin',
    'download' => 'I-download', 
    'update' => 'I-update',
    'file-mode' => 'Mode ng File', 
    'you-cant-recover' => 'Hindi mo na mababawi ang mga nilalaman ng', 
    'once-deleted' => 'kapag na-delete.', 
    'delete-files' => 'Tanggalin ang Mga File',
    'are-you-sure' => 'Sigurado ka bang gusto mong tanggalin ang', 
    'this-is-permanent-action' => 'Ito ay isang permanenteng aksyon at hindi na mababawi ang mga file.', 
    'name' => 'pangalan',
    'size' => 'laki', 
    'date' => 'petsa', 
    'home' => 'home', 
    'container' => 'container', 
    'is-empty' => 'Mukhang walang laman ang direktoryong ito.', 
    'is-limited' => 'Masyadong malaki ang direktoryong ito para ipakita sa browser. Nili-limit ang display output sa unang 250 file.', 
    'are-upload-click-to-view' => 'Nag-a-upload ang mga file, i-click para makita', 
    'cancel-uploads' => 'Kanselahin ang Mga Upload', 
    'cancel' => 'Kanselahin',
    'close' => 'Isara',
    'create' => 'Gumawa',
    'file-name' => 'Pangalan ng File', 
    'file-name-description' => 'Ilagay ang pangalan kung saan dapat i-save ang file na ito.', 
    'directory-will-be-as' => 'Gagawin ang direktoryong ito bilang',
    'rename-description' => 'Ilagay ang bagong pangalan at direktoryo ng file o folder na ito, kaugnay sa kasalukuyang direktoryo.', 
    'new-location' => 'Bagong lokasyon', 
    'drag-and-drop' => 'I-drag and drop ang mga file para mag-upload.', 

    'edit' => [
        'youre-editing' => 'Ine-edit mo ang isang', 
        'will-be-exluded' => 'file. Lahat ng  file o direktoryo na nakalista dito ay hindi kasama sa mga backup. Sinusuportahan ang mga wildcard gamit ang asterisk', 
        'you-can-negate' => 'Maaari mong i-negate ang naunang panuntunan sa pamamagitan ng paglalagay ng exclamation point', 
        'save-content' => 'I-save ang Nilalaman',
        'create-file' => 'Gumawa ng File',
    ],
];
