<?php

return [
    'file-manager' => 'Menadżer plików',
    'search' => 'Szukaj',
    'delete' => 'Usuń',
    'move' => 'Przenieś',
    'archive' => 'Archiwizuj',
    'unarchive' => 'Odkoduj',
    'create-directory' => 'Utwórz katalog',
    'upload' => 'Prześlij',
    'new-file' => 'Nowy plik',
    'rename' => 'Zmień nazwę',
    'permissions' => 'Uprawnienia',
    'copy' => 'Kopiuj',
    'download' => 'Pobierz',
    'update' => 'Aktualizuj',
    'file-mode' => 'Tryb pliku',
    'you-cant-recover' => 'Nie będziesz w stanie odzyskać zawartości',
    'once-deleted' => 'po usunięciu.',
    'delete-files' => 'Usuń pliki',
    'are-you-sure' => 'Czy na pewno chcesz usunąć',
    'this-is-permanent-action' => 'To jest trwała operacja i pliki nie mogą być odzyskane.',
    'name' => 'nazwa',
    'size' => 'rozmiar',
    'date' => 'data',
    'home' => 'home',
    'container' => 'kontener',
    'is-empty' => 'Ten katalog wydaje się być pusty.',
    'is-limited' => 'Ten katalog jest zbyt duży, aby wyświetlić go w przeglądarce, więc wyświetlam tylko pierwsze 250 plików.',
    'are-upload-click-to-view' => 'pliki są przesyłane, kliknij, aby zobaczyć',
    'cancel-uploads' => 'Anuluj przesyłanie',
    'cancel' => 'Anuluj',
    'close' => 'Zamknij',
    'create' => 'Utwórz',
    'file-name' => 'Nazwa pliku',
    'file-name-description' => 'Wprowadź nazwę, pod jaką ma być zapisany ten plik.',
    'directory-will-be-as' => 'Ten katalog zostanie utworzony jako',
    'rename-description' => 'Wprowadź nową nazwę i katalog tego pliku lub folderu, w stosunku do bieżącego katalogu.',
    'new-location' => 'Nowa lokalizacja',
    'drag-and-drop' => 'Przeciągnij i upuść pliki, aby przesłać.',

    'edit' => [
        'youre-editing' => 'Edytujesz',
        'will-be-exluded' => 'plik. Wszystkie pliki lub katalogi wymienione tutaj zostaną pominięte podczas tworzenia kopii zapasowych. Można używać symboli wieloznacznych, dodając gwiazdkę',
        'you-can-negate' => 'Możesz negować wcześniejsze reguły, poprzedzając je wykrzyknikiem',
        'save-content' => 'Zapisz zawartość',
        'create-file' => 'Utwórz plik',
    ],
];
