<?php 

return [
    'schedules' => 'Harmonogramy',
    'manage-schedules' => 'Zarządzaj harmonogramami',
    'create-schedule' => 'Utwórz harmonogram',
    'name' => 'Nazwa',
    'last-run-at' => 'Ostatnie uruchomienie',
    'next-run-at' => 'Następne uruchomienie',
    'status' => 'Status',
    'active' => 'Aktywny',
    'inactive' => 'Nieaktywny',
    'processing' => 'Przetwarzanie',
    'manage-schedule' => 'Zarządzaj harmonogramem',
    'new-task' => 'Nowe zadanie',
    'run-now' => 'Uruchom teraz',
    'editBtn' => 'Edytuj',
    'n/a' => 'brak danych',
    'never' => 'nigdy',

    'no-schedules' => 'Nie ma skonfigurowanych harmonogramów dla tego serwera.',
    'ignore-files-folders' => 'Ignorowanie plików i folderów',
    'continues-on-failure' => 'Kontynuuj w przypadku niepowodzenia',
    'later' => 'później',

    'minute' => 'Minuta',
    'hour' => 'Godzina',
    'day' => 'Dzień',
    'week' => 'Tydzień',
    'day-of-month' => 'Dzień miesiąca',
    'month' => 'Miesiąc',
    'day-of-week' => 'Dzień tygodnia',

    'deleteTask' => [
        'title' => 'Potwierdź usunięcie zadania',
        'description' => 'Czy na pewno chcesz usunąć to zadanie? Ta operacja nie może być cofnięta.',
        'delete' => 'Usuń zadanie'
    ],
    'delete' => [
        'title' => 'Usuń harmonogram',
        'description' => 'Wszystkie zadania zostaną usunięte, a wszystkie uruchomione procesy zostaną zakończone.',
        'delete' => 'Usuń'
    ],
    'edit' => [
        'title-1' => 'Edytuj harmonogram',
        'title-2' => 'Utwórz nowy harmonogram',

        'description' => 'System harmonogramu obsługuje użycie składni Cronjob przy definiowaniu, kiedy zadania mają się rozpocząć. Użyj powyższych pól, aby określić, kiedy te zadania mają się rozpocząć.',
        
        'name' => 'Nazwa harmonogramu',
        'name-description' => 'Czytelny identyfikator dla tego harmonogramu.',
        'cheatsheet' => 'Pokaż ściągawkę',
        'cheatsheet-description' => 'Pokaż ściągawkę cron z przykładami',
        'online-when-online' => 'Tylko gdy serwer jest online',
        'online-when-online-description' => 'Wykonaj ten harmonogram tylko wtedy, gdy serwer jest w stanie uruchomionym.',
        'enabled' => 'Harmonogram włączony',
        'enabled-description' => 'Ten harmonogram zostanie wykonany automatycznie, jeśli jest włączony.',

        'save-changes' => 'Zapisz zmiany',
    ],
    'cheatsheet' => [
        'example' => 'Przykłady',
        'every-5-minutes' => 'co 5 minut',
        'every-hour' => 'co godzinę',
        'hour-range' => 'zakres godzin',
        'once-a-day' => 'raz dziennie',
        'every-monday' => 'każdy poniedziałek',
        'special-characters' => 'Znaki specjalne',
        'any-value' => 'dowolna wartość',
        'value-list-separator' => 'separator listy wartości',
        'range-values' => 'zakres wartości',
        'step-values' => 'wartości kroków',
    ],
    'task' => [
        'message' => 'Zadanie tworzenia kopii zapasowej nie może zostać utworzone, gdy limit kopii zapasowych serwera jest ustawiony na 0.',
        'edit-task' => 'Edytuj zadanie',
        'save-changes' => 'Zapisz zmiany',
        'create-task' => 'Utwórz zadanie',
        'action' => 'Akcja',
        'send-command' => 'Wyślij komendę',
        'send-power-action' => 'Wyślij akcję zasilania',
        'create-backup' => 'Utwórz kopię zapasową',
        'offset' => 'Opóźnienie czasowe (w sekundach)',
        'offset-description' => 'Czas oczekiwania po wykonaniu poprzedniego zadania przed uruchomieniem tego. Jeśli jest to pierwsze zadanie w harmonogramie, to nie zostanie zastosowane.',
        'payload' => 'Ładunek',
        'ignored-files' => 'Ignorowane pliki',
        'ignored-files-description' => 'Opcjonalnie. Dołącz pliki i foldery, które mają być wykluczone z tej kopii zapasowej. Domyślnie zostanie użyta zawartość pliku .pteroignore. Jeśli osiągnąłeś limit kopii zapasowych, najstarsza kopia zostanie zamieniona.',
        'start-server' => 'Uruchom serwer',
        'stop-server' => 'Zatrzymaj serwer',
        'restart-server' => 'Restartuj serwer',
        'kill-server' => 'Zakończ serwer',
        'continue-on-failure' => 'Kontynuuj w przypadku niepowodzenia',
        'continue-on-failure-description' => 'Przyszłe zadania zostaną uruchomione, gdy to zadanie się nie powiedzie.',
    ],
];
