<?php 

return [
    'schedules' => 'Schema\'s',
    'manage-schedules' => 'Beheer schema\'s',
    'create-schedule' => 'Schema maken',
    'name' => 'Naam',
    'last-run-at' => 'Laatst uitgevoerd op',
    'next-run-at' => 'Volgende uitvoering op',
    'status' => 'Status',
    'active' => 'Actief',
    'inactive' => 'Inactief',
    'processing' => 'Verwerken',
    'manage-schedule' => 'Schema beheren',
    'new-task' => 'Nieuwe Taak',
    'run-now' => 'Nu uitvoeren',
    'editBtn' => 'Bewerken',
    'n/a' => 'n.v.t.',
    'never' => 'nooit',

    'no-schedules' => 'Er zijn geen schema\'s geconfigureerd voor deze server.',
    'ignore-files-folders' => 'Bestanden & mappen negeren',
    'continues-on-failure' => 'Doorgaan bij fout',
    'later' => 'later',

    'minute' => 'Minuut',
    'hour' => 'Uur',
    'day' => 'Dag',
    'week' => 'Week',
    'day-of-month' => 'Dag van de maand',
    'month' => 'Maand',
    'day-of-week' => 'Dag van de week',

    'deleteTask' => [
        'title' => 'Bevestig verwijdering van taak',
        'description' => 'Weet je zeker dat je deze taak wilt verwijderen? Deze actie kan niet ongedaan worden gemaakt.',
        'delete' => 'Taak verwijderen'
    ],
    'delete' => [
        'title' => 'Schema verwijderen',
        'description' => 'Alle taken worden verwijderd en alle lopende processen worden beëindigd.',
        'delete' => 'Verwijderen'
    ],
    'edit' => [
        'title-1' => 'Schema bewerken',
        'title-2' => 'Nieuw schema maken',

        'description' => 'Het schema-systeem ondersteunt het gebruik van Cronjob-syntaxis bij het definiëren van wanneer taken moeten beginnen met uitvoeren. Gebruik de bovenstaande velden om aan te geven wanneer deze taken moeten beginnen met uitvoeren.',
        
        'name' => 'Naam van het schema',
        'name-description' => 'Een menselijk leesbare identificatie voor dit schema.',
        'cheatsheet' => 'Cheatsheet weergeven',
        'cheatsheet-description' => 'Toon de cron-cheatsheet voor enkele voorbeelden',
        'online-when-online' => 'Alleen wanneer server online is',
        'online-when-online-description' => 'Voer dit schema alleen uit wanneer de server in een actieve staat is.',
        'enabled' => 'Schema ingeschakeld',
        'enabled-description' => 'Dit schema wordt automatisch uitgevoerd indien ingeschakeld.',

        'save-changes' => 'Wijzigingen opslaan',
    ],
    'cheatsheet' => [
        'example' => 'Voorbeelden',
        'every-5-minutes' => 'elke 5 minuten',
        'every-hour' => 'elk uur',
        'hour-range' => 'uurbereik',
        'once-a-day' => 'eenmaal per dag',
        'every-monday' => 'elke maandag',
        'special-characters' => 'Speciale tekens',
        'any-value' => 'elke waarde',
        'value-list-separator' => 'waarde lijstscheidingsteken',
        'range-values' => 'bereikwaarden',
        'step-values' => 'stapwaarden',
    ],
    'task' => [
        'message' => 'Een back-uptaak kan niet worden gemaakt wanneer de back-uplimiet van de server is ingesteld op 0.',
        'edit-task' => 'Taak bewerken',
        'save-changes' => 'Wijzigingen opslaan',
        'create-task' => 'Taak maken',
        'action' => 'Actie',
        'send-command' => 'Opdracht verzenden',
        'send-power-action' => 'Energieactie verzenden',
        'create-backup' => 'Back-up maken',
        'offset' => 'Tijdverschil (in seconden)',
        'offset-description' => 'De tijd die moet worden gewacht nadat de vorige taak is uitgevoerd voordat deze wordt uitgevoerd. Als dit de eerste taak op een schema is, wordt dit niet toegepast.',
        'payload' => 'Lading',
        'ignored-files' => 'Genegeerde bestanden',
        'ignored-files-description' => 'Optioneel. Geef de bestanden en mappen op die moeten worden uitgesloten in deze back-up. Standaard worden de inhoud van uw .pteroignore-bestand gebruikt. Als u uw back-uplimiet heeft bereikt, wordt de oudste back-up geroteerd.',
        'start-server' => 'Start de server',
        'stop-server' => 'Stop de server',
        'restart-server' => 'Herstart de server',
        'kill-server' => 'Beëindig de server',
        'continue-on-failure' => 'Doorgaan bij fout',
        'continue-on-failure-description' => 'Toekomstige taken worden uitgevoerd wanneer deze taak mislukt.',
    ],
];