<?php 

return [
    'schedules' => 'Mga Iskedyul',
    'manage-schedules' => 'Pamahalaan ang mga iskedyul',
    'create-schedule' => 'Gumawa ng iskedyul', 
    'name' => 'Pangalan',
    'last-run-at' => 'Huling pinatakbo noong',
    'next-run-at' => 'Susunod na pagtakbo sa',
    'status' => 'Katayuan', 
    'active' => 'Aktibo',
    'inactive' => 'Hindi Aktibo',
    'processing' => 'Pinoproseso', 
    'manage-schedule' => 'Pamahalaan ang iskedyul',
    'new-task' => 'Bagong Task',
    'run-now' => 'Patakbuhin Ngayon',
    'editBtn' => 'I-edit',
    'n/a' => 'n/a',
    'never' => 'hindi kailanman',

    'no-schedules' => 'Walang mga iskedyul na naka-configure para sa server na ito.',
    'ignore-files-folders' => 'Hindi papansinin ang mga file at folder', 
    'continues-on-failure' => 'Magpapatuloy Kahit Mabigo', 
    'later' => 'maya-maya', 

    'minute' => 'Minuto',
    'hour' => 'Oras',
    'day' => 'Araw', 
    'week' => 'Linggo', 
    'day-of-month' => 'Araw ng buwan',
    'month' => 'Buwan',
    'day-of-week' => 'Araw ng linggo',

    'deleteTask' => [
        'title' => 'Kumpirmahin ang pagtanggal ng task',
        'description' => 'Sigurado ka bang gusto mong tanggalin ang task na ito? Hindi na mababawi ang aksyon na ito.',
        'delete' => 'Tanggalin ang Task' 
    ],
    'delete' => [
        'title' => 'Tanggalin ang Schedule',
        'description' => 'Aalisin ang lahat ng task at papatayin ang anumang tumatakbo na mga proseso.',
        'delete' => 'Tanggalin' 
    ],
    'edit' => [
        'title-1' => 'I-edit ang iskedyul',
        'title-2' => 'Gumawa ng bagong iskedyul',

        'description' => 'Ang schedule system ay sumusuporta sa paggamit ng syntax ng Cronjob kapag dini-define kung kailan dapat magsimulang tumakbo ang mga task. Gamitin ang mga fields sa itaas para magtakda kung kailan dapat magsimula ang mga task na ito.', 

        'name' => 'Pangalan ng iskedyul',
        'name-description' => 'Isang identifier na nababasa ng tao para sa iskedyul na ito.',
        'cheatsheet' => 'Ipakita ang Cheatsheet',
        'cheatsheet-description' => 'Ipakita ang cron cheatsheet para sa ilang halimbawa',
        'online-when-online' => 'Kapag Online Lamang ang Server', 
        'online-when-online-description' => 'Isagawa lamang ang iskedyul na ito kapag ang server ay nasa running state.', 
        'enabled' => 'Na-enable ang Iskedyul',
        'enabled-description' => 'Awtomatikong gagawin ang iskedyul na ito kung naka-enable.',

        'save-changes' => 'I-save ang mga pagbabago',
    ],
    'cheatsheet' => [
        'example' => 'Mga halimbawa',
        'every-5-minutes' => 'bawat 5 minuto', 
        'every-hour' => 'bawat oras',
        'hour-range' => 'saklaw ng oras', 
        'once-a-day' => 'minsan isang araw', 
        'every-monday' => 'bawat Lunes', 
        'special-characters' => 'Mga Espesyal na Character', 
        'any-value' => 'anumang value', 
        'value-list-separator' => 'separator ng listahan ng value',
        'range-values' => 'mga value ng saklaw', 
        'step-values' => 'mga value ng hakbang', 
    ],
    'task' => [
        'message' => 'Hindi makakagawa ng backup task kapag ang backup limit ng server ay nakatakda sa 0.',
        'edit-task' => 'I-edit ang Task', 
        'save-changes' => 'I-save ang mga Pagbabago',
        'create-task' => 'Gumawa ng Task', 
        'action' => 'Aksyon', 
        'send-command' => 'Magpadala ng command',
        'send-power-action' => 'Magpadala ng power action',
        'create-backup' => 'Gumawa ng backup', 
        'offset' => 'Time offset (sa segundo)',
        'offset-description' => 'Ang dami ng oras na hihintayin pagkatapos maisakatuparan ang nakaraang task bago patakbuhin ang isang ito. Kung ito ang unang task sa isang iskedyul, hindi ito ia-apply.',
        'payload' => 'Payload',
        'ignored-files' => 'Mga Hindi Papansinin na File',
        'ignored-files-description' => 'Opsyonal. Isama ang mga file at folder na isasama sa backup na ito. Bilang default, gagamitin ang mga nilalaman ng iyong .pteroignore file. Kapag naabot mo na ang iyong backup limit, iro-rotate ang pinakamatandang backup.',
        'start-server' => 'Simulan ang server', 
        'stop-server' => 'Ihinto ang server', 
        'restart-server' => 'I-restart ang server', 
        'kill-server' => 'Wakasan ang server', 
        'continue-on-failure' => 'Magpatuloy Kahit Mabigo', 
        'continue-on-failure-description' => 'Patatakbuhinang mga task sa hinaharap kapag nabigo ang task na ito.',
    ],
];
