<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Se porneste',
    'stopping' => 'Se opreste',
    'suspended' => 'Suspendat',
    'connection-error' => 'Eroare de Conexiune',
    'transferring' => 'Se transfera',
    'installing' => 'Se instaleaza',
    'restoring-backup' => 'Restaurarea backup-ului',
    'unavailable' => 'Nu este valabil',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Memorie',
    'disk' => 'Disk',
    'unlimited' => 'Nelimitat',
    'start' => 'Porneste',
    'restart' => 'Restarteaza',
    'stop' => 'Opreste',
    'kill' => 'Kill',
    'forcibly-stop-process' => 'Oprirea fortata a procesului',
    'continue' => 'Continue',
    'forcibly-stopping-alert' => 'Oprirea foratata a unui server poate duce la coruperea datelor.',
    'cpu-usage' => 'Utilizarea CPU',
    'memory-usage' => 'Utilizarea Memoriei',
    'disk-usage' => 'Utilizarea Disk-ului',
    'inbound-outbound' => 'Sosire / Plecare',
    'low-resources' => 'Resurse reduse',
    'low-resources-desc' => 'Server-ul tau ruleaza pe resurse reduse, te rog actualizeaza-ti planul',
    'upgrade-server' => 'Upgrade Server',
    'cancel' => 'Anuleaza',
    'copied-text' => 'S-a copiat {{text}} in clipboard-ul tau.',
    'showing' => 'Se afiseaza',
    'to' => 'la',
    'of' => 'din',
    'results' => 'rezultate.',
];
