<?php

return [
    'online' => 'ऑनलाइन',
    'offline' => 'ऑफ़लाइन',
    'starting' => 'शुरू हो रहा है',
    'stopping' => 'बंद हो रहा है',
    'suspended' => 'निलंबित',
    'connection-error' => 'कनेक्शन त्रुटि',
    'transferring' => 'स्थानांतरित हो रहा है',
    'installing' => 'इंस्टॉल हो रहा है',
    'restoring-backup' => 'बैकअप पुनर्स्थापित हो रहा है',
    'unavailable' => 'उपलब्ध नहीं',
    'status' => 'स्थिति',
    'CPU' => 'CPU',
    'memory' => 'मेमोरी',
    'disk' => 'डिस्क',
    'unlimited' => 'अनलिमिटेड',
    'start' => 'शुरू करें',
    'restart' => 'रीस्टार्ट करें',
    'stop' => 'रोकें',
    'kill' => 'ज़बरदस्ती बंद करें',
    'forcibly-stop-process' => 'प्रक्रिया को ज़बरदस्ती रोकें',
    'continue' => 'जारी रखें',
    'forcibly-stopping-alert' => 'सर्वर को ज़बरदस्ती रोकना डेटा करप्शन का कारण बन सकता है।',
    'cpu-usage' => 'CPU उपयोग',
    'memory-usage' => 'मेमोरी उपयोग',
    'disk-usage' => 'डिस्क उपयोग',
    'inbound-outbound' => 'इनबाउंड / आउटबाउंड',
    'low-resources' => 'कम संसाधन',
    'low-resources-desc' => 'आपका सर्वर संसाधनों पर कम है, यह गंभीर हो सकता है, कृपया अपनी योजना अपग्रेड करें।',
    'upgrade-server' => 'सर्वर अपग्रेड करें',
    'cancel' => 'रद्द करें',
    'copied-text' => '{{text}} क्लिपबोर्ड पर कॉपी किया गया।',
    'showing' => 'दिखा रहा है',
    'to' => 'तक',
    'of' => 'में से',
    'results' => 'परिणाम।',
];
