<?php

return [
    'online' => 'آن لائن',
    'offline' => 'آف لائن',
    'starting' => 'شروع ہو رہا ہے',
    'stopping' => 'روک رہا ہے',
    'suspended' => 'معلق',
    'connection-error' => 'کنکشن خرابی',
    'transferring' => 'منتقلی',
    'installing' => 'انسٹال ہو رہا ہے',
    'restoring-backup' => 'بیک اپ بحال ہو رہا ہے',
    'unavailable' => 'دستیاب نہیں',
    'status' => 'حالت',
    'CPU' => 'سی پی یو',
    'memory' => 'میموری',
    'disk' => 'ڈسک',
    'unlimited' => 'لامحدود',
    'start' => 'شروع کریں',
    'restart' => 'دوبارہ چلائیں',
    'stop' => 'روکیں',
    'kill' => 'کل کریں',
    'forcibly-stop-process' => 'جبری طور پر پروسیس روکیں',
    'continue' => 'جاری رہے',
    'forcibly-stopping-alert' => 'سرور کو جبری طور پر روکنا ڈیٹا کرپشن کا باعث ہو سکتا ہے۔',
    'cpu-usage' => 'سی پی یو کا استعمال',
    'memory-usage' => 'میموری کا استعمال',
    'disk-usage' => 'ڈسک کا استعمال',
    'inbound-outbound' => 'آن باؤنڈ / آؤٹ باؤنڈ',
    'low-resources' => 'معدوم وسائل',
    'low-resources-desc' => 'آپ کا سرور وسائل پر کم ہے، یہ سنجیدہ ہو سکتا ہے، براہ کرم اپنے منصوبے کو اپ گریڈ کریں',
    'upgrade-server' => 'سرور کو اپ گریڈ کریں',
    'cancel' => 'منسوخ کریں',
    'copied-text' => '{{text}} کلپ بورڈ پر کاپی ہوگیا۔',
    'showing' => 'دکھا رہا ہے',
    'to' => 'سے',
    'of' => 'کا',
    'results' => 'نتائج۔',
];
