<?php

return [
    'file-manager' => 'Файлы',
    'search' => 'Поиск',
    'delete' => 'Удалить',
    'move' => 'Переместить',
    'archive' => 'Архивировать',
    'unarchive' => 'Разархивировать',
    'create-directory' => 'Создать папку',
    'upload' => 'Загрузить',
    'new-file' => 'Новый файл',
    'rename' => 'Переименовать',
    'permissions' => 'Права доступа',
    'copy' => 'Копировать',
    'download' => 'Скачать',
    'update' => 'Обновить',
    'file-mode' => 'Права файла',
    'you-cant-recover' => 'Вы не сможете восстановить содержимое',
    'once-deleted' => 'после удаления.',
    'delete-files' => 'Удалить файлы',
    'are-you-sure' => 'Вы уверены, что хотите удалить',
    'this-is-permanent-action' => 'Это постоянное действие, и файлы не могут быть восстановлены.',
    'name' => 'Имя',
    'size' => 'Размер',
    'date' => 'Дата',
    'home' => 'Домой',
    'container' => 'Контейнер',
    'is-empty' => 'Этот каталог кажется пустым.',
    'is-limited' => 'Этот каталог слишком велик для отображения в браузере, вывод ограничен первыми 250 файлами.',
    'are-upload-click-to-view' => 'файлов загружаются, нажмите, чтобы посмотреть',
    'cancel-uploads' => 'Отменить загрузки',
    'cancel' => 'Отмена',
    'close' => 'Закрыть',
    'create' => 'Создать',
    'file-name' => 'Имя файла',
    'file-name-description' => 'Введите имя, под которым следует сохранить этот файл.',
    'directory-will-be-as' => 'Этот каталог будет создан как',
    'rename-description' => 'Введите новое имя и каталог для этого файла или папки, относительно текущего каталога.',
    'new-location' => 'Новое местоположение',
    'drag-and-drop' => 'Перетащите файлы для загрузки.',


    'folders-not-supported' => 'Folder uploads are not supported at this time.',
    'upload-files' => 'Upload Files',
    'folder-too-big' => 'Folder size exceeds 10MB limit. Please select a smaller folder.',
    'upload-folders' => 'Upload Folders',
    'upload-from-url' => 'Upload from URL',
    'filename' => 'Filename',
    'open-code-editor' => 'Open Code Editor',

    'code-editor' => [
        'explorer' => 'Explorer',
        'reload' => 'Reload',
        'new' => 'New',
        'browse-files' => 'Browse Files',
        'save' => 'Save',
        'save-dirty' => 'Save *',
        'saving' => 'Saving...',
        'no-file-selected' => 'No file selected',
        'no-files-found' => 'No files found',
        'loading' => 'Loading...',

        'file-be-created' => 'This file will be created as',
    ],
    
    'edit' => [
        'youre-editing' => 'Вы редактируете файл',
        'will-be-exluded' => 'Любые файлы или каталоги, перечисленные здесь, будут исключены из резервных копий. Поддерживаются подстановочные символы, используя звездочку',
        'you-can-negate' => 'Вы можете отменить предыдущее правило, добавив восклицательный знак в начало',
        'save-content' => 'Сохранить содержимое',
        'create-file' => 'Создать файл',
    ],
];
