<?php

return [
    'online' => 'Çevrimiçi',
    'offline' => 'Çevrimdışı',
    'starting' => 'Açılıyor',
    'stopping' => 'Durduruluyor',
    'suspended' => 'Askıya Alındı',
    'connection-error' => 'Bağlantı Hatası',
    'transferring' => 'Aktarılıyor',
    'installing' => 'Yükleniyor',
    'restoring-backup' => 'Yedek Geri Yükleniyor',
    'unavailable' => 'Ulaşılamaz',
    'status' => 'Durum',
    'CPU' => 'CPU',
    'memory' => 'Bellek',
    'disk' => 'Disk',
    'unlimited' => 'Sınırsız',
    'start' => 'Başlat',
    'restart' => 'Yeniden Başlat',
    'stop' => 'Durdur',
    'kill' => 'Sonlandır',
    'forcibly-stop-process' => 'Zorla İşlem Durdur',
    'continue' => 'Devam Et',
    'forcibly-stopping-alert' => 'Bir sunucuyu zorla durdurmak veri bozulmasına neden olabilir.',
    'cpu-usage' => 'CPU Kullanımı',
    'memory-usage' => 'Bellek Kullanımı',
    'disk-usage' => 'Disk Kullanımı',
    'inbound-outbound' => 'Gelen / Giden',
    'low-resources' => 'Düşük Kaynaklar',
    'low-resources-desc' => 'Sunucunuzun kaynakları yetersiz, sunucu planınızı yükseltmeyi düşünün',
    'upgrade-server' => 'Sunucuyu Yükselt',
    'cancel' => 'İptal',
    'copied-text' => '{{text}} panoya kopyalandı.',
    'showing' => 'Gösteriliyor',
    'to' => '',
    'of' => '',
    'results' => 'sonuçlar.',

];
