<?php

return [
    'online' => 'Tændt',
    'offline' => 'Slukket',
    'starting' => 'Starter',
    'stopping' => 'Stopper',
    'suspended' => 'Suspenderet',
    'connection-error' => 'Forbindelsesfejl',
    'transferring' => 'Overførsel',
    'installing' => 'Installerer',
    'restoring-backup' => 'Gendannelse af sikkerhedskopi',
    'unavailable' => 'Utilgængelig',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Hukommelse',
    'disk' => 'Plads',
    'unlimited' => 'Ubegrænset',
    'start' => 'Start',
    'restart' => 'Genstart',
    'stop' => 'Stop',
    'kill' => 'Dræb',
    'forcibly-stop-process' => 'Stopprocessen med magt',
    'continue' => 'Fortsæt',
    'forcibly-stopping-alert' => 'Konkurrence med at stoppe en server kan føre til datakorruption.',
    'cpu-usage' => 'CPU forbrug',
    'memory-usage' => 'Hukommelsesforbrug',
    'disk-usage' => 'Pladsforbrug',
    'inbound-outbound' => 'Indgående udgående',
    'low-resources' => 'Lav på ressourcer',
    'low-resources-desc' => 'Din server løber lavt på ressourcerne, sørg for at opgradere din plan!',
    'upgrade-server' => 'Opgrader server',
    'cancel' => 'Afbestil',
    'copied-text' => 'Kopieret {{text}} til udklipsholder.',
    'showing' => 'Vises',
    'to' => 'til',
    'of' => 'af',
    'results' => 'resultater.',
];
