<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'In avvio',
    'stopping' => 'In arresto',
    'suspended' => 'Sospeso',
    'connection-error' => 'Errore di connessione',
    'transferring' => 'Trasferimento',
    'installing' => 'Installazione',
    'restoring-backup' => 'Ripristino Backup',
    'unavailable' => 'Non disponibile',
    'status' => 'Stato',
    'CPU' => 'CPU',
    'memory' => 'Memoria',
    'disk' => 'Disco',
    'unlimited' => 'Illimitato',
    'start' => 'Avvia',
    'restart' => 'Riavvia',
    'stop' => 'Arresta',
    'kill' => 'Termina',
    'forcibly-stop-process' => 'Arresto Forzato del Processo',
    'continue' => 'Continua',
    'forcibly-stopping-alert' => 'Arrestare forzatamente un server può causare la corruzione dei dati.',
    'cpu-usage' => 'Utilizzo CPU',
    'memory-usage' => 'Utilizzo Memoria',
    'disk-usage' => 'Utilizzo Disco',
    'inbound-outbound' => 'In entrata / In uscita',
    'low-resources' => 'Pochi risorse',
    'low-resources-desc' => 'Il tuo server sta esaurendo le risorse, assicurati di aggiornare il tuo piano',
    'upgrade-server' => 'Aggiorna Server',
    'cancel' => 'Annulla',
    'copied-text' => '{{text}} copiato negli appunti.',
    'showing' => 'Visualizzazione',
    'to' => 'a',
    'of' => 'di',
    'results' => 'risultati.',
];
