<?php

return [
    'file-manager' => '파일 관리자',
    'search' => '검색',
    'delete' => '삭제',
    'move' => '이동',
    'archive' => '압축',
    'unarchive' => '압축 해제',
    'create-directory' => '디렉터리 생성',
    'upload' => '업로드',
    'new-file' => '새 파일',
    'rename' => '이름 바꾸기',
    'permissions' => '권한',
    'copy' => '복사',
    'download' => '다운로드',
    'update' => '업데이트',
    'file-mode' => '파일 모드',
    'you-cant-recover' => '다음 내용을 복구할 수 없습니다:',
    'once-deleted' => '일단 삭제하면 복원할 수 없습니다.',
    'delete-files' => '파일 삭제',
    'are-you-sure' => '다음을 삭제하시겠습니까:',
    'this-is-permanent-action' => '이 작업은 영구적이며 파일을 복구할 수 없습니다.',
    'name' => '이름',
    'size' => '크기',
    'date' => '날짜',
    'home' => '홈',
    'container' => '컨테이너',
    'is-empty' => '이 디렉터리는 비어있는 것으로 보입니다.',
    'is-limited' => '이 디렉터리는 브라우저에 표시하기에 너무 큽니다. 출력이 처음 250개의 파일로 제한되었습니다.',
    'are-upload-click-to-view' => '파일이 업로드되고 있습니다. 클릭하여 보기',
    'cancel-uploads' => '업로드 취소',
    'cancel' => '취소',
    'close' => '닫기',
    'create' => '생성',
    'file-name' => '파일 이름',
    'file-name-description' => '이 파일을 저장할 이름을 입력하세요.',
    'directory-will-be-as' => '이 디렉터리는 다음으로 생성됩니다:',
    'rename-description' => '이 파일 또는 폴더의 새 이름 및 디렉터리를 현재 디렉터리를 기준으로 입력하세요.',
    'new-location' => '새 위치',
    'drag-and-drop' => '업로드하려면 파일을 끌어다 놓으세요.',

    'edit' => [
        'youre-editing' => '편집 중인',
        'will-be-exluded' => '파일입니다. 여기에 나열된 모든 파일 또는 디렉터리는 백업에서 제외됩니다. 와일드카드는 별표를 사용하여 지원됩니다.',
        'you-can-negate' => '먼저 작성된 규칙을 반전시킬 수 있습니다.',
        'save-content' => '콘텐츠 저장',
        'create-file' => '파일 생성',
    ],
];
