<?php

return [
    'file-manager' => 'Gestore File',
    'search' => 'Cerca',
    'delete' => 'Elimina',
    'move' => 'Sposta',
    'archive' => 'Archivia',
    'unarchive' => 'Decomprimi',
    'create-directory' => 'Crea Directory',
    'upload' => 'Carica',
    'new-file' => 'Nuovo file',
    'rename' => 'Rinomina',
    'permissions' => 'Permessi',
    'copy' => 'Copia',
    'download' => 'Scarica',
    'update' => 'Aggiorna',
    'file-mode' => 'Modalità File',
    'you-cant-recover' => 'Non sarai in grado di recuperare i contenuti di',
    'once-deleted' => 'una volta eliminato.',
    'delete-files' => 'Elimina Files',
    'are-you-sure' => 'Sei sicuro di voler eliminare',
    'this-is-permanent-action' => 'Questa è un\'azione permanente e i file non possono essere recuperati.',
    'name' => 'nome',
    'size' => 'dimensione',
    'date' => 'data',
    'home' => 'home',
    'container' => 'contenitore',
    'is-empty' => 'Questa directory sembra essere vuota.',
    'is-limited' => 'Questa directory è troppo grande per essere visualizzata nel browser, limitando l\'output ai primi 250 file.',
    'are-upload-click-to-view' => 'file sono in fase di caricamento, clicca per visualizzare',
    'cancel-uploads' => 'Annulla Caricamenti',
    'cancel' => 'Annulla',
    'close' => 'Chiudi',
    'create' => 'Crea',
    'file-name' => 'Nome File',
    'file-name-description' => 'Inserisci il nome con cui salvare questo file.',
    'directory-will-be-as' => 'Questa directory verrà creata come',
    'rename-description' => 'Inserisci il nuovo nome e la nuova directory di questo file o cartella, relativamente alla directory corrente.',
    'new-location' => 'Nuova posizione',
    'drag-and-drop' => 'Trascina e rilascia i file per caricarli.',


    'folders-not-supported' => 'Il caricamento di cartelle non è attualmente supportato.',
    'upload-files' => 'Carica file',
    'folder-too-big' => 'La dimensione della cartella supera il limite di 10 MB. Seleziona una cartella più piccola.',
    'upload-folders' => 'Carica cartelle',
    'upload-from-url' => 'Carica da URL',
    'filename' => 'Nome file',
    'open-code-editor' => 'Apri editor di codice',

    'code-editor' => [
        'explorer' => 'Explorer',
        'reload' => 'Ricarica',
        'new' => 'Nuovo',
        'browse-files' => 'Sfoglia file',
        'save' => 'Salva',
        'save-dirty' => 'Salva *',
        'saving' => 'Salvataggio...',
        'no-file-selected' => 'Nessun file selezionato',
        'no-files-found' => 'Nessun file trovato',
        'loading' => 'Caricamento...',

        'file-be-created' => 'Questo file verrà creato come',
    ],
    
    'edit' => [
        'youre-editing' => 'Stai modificando un',
        'will-be-exluded' => 'file. Qualsiasi file o directory elencati qui sarà escluso dai backup. I caratteri jolly sono supportati utilizzando un asterisco',
        'you-can-negate' => 'Puoi annullare una regola precedente anteponendo un punto esclamativo',
        'save-content' => 'Salva Contenuto',
        'create-file' => 'Crea File',
    ],
];
