<?php

return [
    'file-manager' => 'Gestore File',
    'search' => 'Cerca',
    'delete' => 'Elimina',
    'move' => 'Sposta',
    'archive' => 'Archivia',
    'unarchive' => 'Decomprimi',
    'create-directory' => 'Crea Directory',
    'upload' => 'Carica',
    'new-file' => 'Nuovo file',
    'rename' => 'Rinomina',
    'permissions' => 'Permessi',
    'copy' => 'Copia',
    'download' => 'Scarica',
    'update' => 'Aggiorna',
    'file-mode' => 'Modalità File',
    'you-cant-recover' => 'Non sarai in grado di recuperare i contenuti di',
    'once-deleted' => 'una volta eliminato.',
    'delete-files' => 'Elimina Files',
    'are-you-sure' => 'Sei sicuro di voler eliminare',
    'this-is-permanent-action' => 'Questa è un\'azione permanente e i file non possono essere recuperati.',
    'name' => 'nome',
    'size' => 'dimensione',
    'date' => 'data',
    'home' => 'home',
    'container' => 'contenitore',
    'is-empty' => 'Questa directory sembra essere vuota.',
    'is-limited' => 'Questa directory è troppo grande per essere visualizzata nel browser, limitando l\'output ai primi 250 file.',
    'are-upload-click-to-view' => 'file sono in fase di caricamento, clicca per visualizzare',
    'cancel-uploads' => 'Annulla Caricamenti',
    'cancel' => 'Annulla',
    'close' => 'Chiudi',
    'create' => 'Crea',
    'file-name' => 'Nome File',
    'file-name-description' => 'Inserisci il nome con cui salvare questo file.',
    'directory-will-be-as' => 'Questa directory verrà creata come',
    'rename-description' => 'Inserisci il nuovo nome e la nuova directory di questo file o cartella, relativamente alla directory corrente.',
    'new-location' => 'Nuova posizione',
    'drag-and-drop' => 'Trascina e rilascia i file per caricarli.',


    'folders-not-supported' => 'Folder uploads are not supported at this time.',
    'upload-files' => 'Upload Files',
    'folder-too-big' => 'Folder size exceeds 10MB limit. Please select a smaller folder.',
    'upload-folders' => 'Upload Folders',
    'upload-from-url' => 'Upload from URL',
    'filename' => 'Filename',
    'open-code-editor' => 'Open Code Editor',

    'code-editor' => [
        'explorer' => 'Explorer',
        'reload' => 'Reload',
        'new' => 'New',
        'browse-files' => 'Browse Files',
        'save' => 'Save',
        'save-dirty' => 'Save *',
        'saving' => 'Saving...',
        'no-file-selected' => 'No file selected',
        'no-files-found' => 'No files found',
        'loading' => 'Loading...',

        'file-be-created' => 'This file will be created as',
    ],
    
    'edit' => [
        'youre-editing' => 'Stai modificando un',
        'will-be-exluded' => 'file. Qualsiasi file o directory elencati qui sarà escluso dai backup. I caratteri jolly sono supportati utilizzando un asterisco',
        'you-can-negate' => 'Puoi annullare una regola precedente anteponendo un punto esclamativo',
        'save-content' => 'Salva Contenuto',
        'create-file' => 'Crea File',
    ],
];
