<?php

return [
    'file-manager' => 'Failų tvarkyklė',
    'search' => 'Paieška',
    'delete' => 'Ištrinti',
    'move' => 'Perkelti',
    'archive' => 'Archyvuoti',
    'unarchive' => 'Išarchyvuoti',
    'create-directory' => 'Sukurti katalogą',
    'upload' => 'Įkelti',
    'new-file' => 'Naujas failas',
    'rename' => 'Pervadinti',
    'permissions' => 'Teisės',
    'copy' => 'Kopijuoti',
    'download' => 'Atsisiųsti',
    'update' => 'Atnaujinti',

    'file-mode' => 'Failo teisės',
    'you-cant-recover' => 'Nebegalėsite atkurti turinio',
    'once-deleted' => 'kai ištrinsite.',
    'delete-files' => 'Ištrinti failus',
    'are-you-sure' => 'Ar tikrai norite ištrinti',
    'this-is-permanent-action' => 'Tai yra negrįžtamas veiksmas ir failai nebegalės būti atkurti.',
    'name' => 'pavadinimas',
    'size' => 'dydis',
    'date' => 'data',
    'home' => 'pagrindinis',
    'container' => 'konteineris',
    'is-empty' => 'Atrodo, kad šis katalogas yra tuščias.',
    'is-limited' => 'Šis katalogas yra per didelis, kad būtų rodomas naršyklėje, rodant pirmuosius 250 failų.',
    'are-upload-click-to-view' => 'failai įkeliami, spustelėkite norėdami peržiūrėti',
    'cancel-uploads' => 'Atšaukti įkėlimus',
    'cancel' => 'Atšaukti',
    'close' => 'Uždaryti',
    'create' => 'Sukurti',
    'file-name' => 'Failo pavadinimas',
    'file-name-description' => 'Įveskite pavadinimą, kuriuo šis failas turėtų būti išsaugotas.',
    'directory-will-be-as' => 'Šis katalogas bus sukurtas kaip',
    'rename-description' => 'Įveskite naują pavadinimą ir katalogą šiam failui ar aplankui, atsižvelgiant į dabartinį katalogą.',
    'new-location' => 'Nauja vieta',
    'drag-and-drop' => 'Tempkite ir numeskite failus įkėlimui.',

    'folders-not-supported' => 'Aplankų įkėlimas šiuo metu nepalaikomas.',
    'upload-files' => 'Įkelti failus',
    'folder-too-big' => 'Aplanko dydis viršija 10MB limitą. Pasirinkite mažesnį aplanką.',
    'upload-folders' => 'Įkelti aplankus',
    'upload-from-url' => 'Įkelti iš URL',
    'filename' => 'Failo pavadinimas',
    'open-code-editor' => 'Atidaryti kodo redaktorių',

    'code-editor' => [
        'explorer' => 'Naršyklė',
        'reload' => 'Įkelti iš naujo',
        'new' => 'Naujas',
        'browse-files' => 'Naršyti failus',
        'save' => 'Išsaugoti',
        'save-dirty' => 'Išsaugoti *',
        'saving' => 'Išsaugoma...',
        'no-file-selected' => 'Nepasirinktas joks failas',
        'no-files-found' => 'Nerasta jokių failų',
        'loading' => 'Įkeliama...',

        'file-be-created' => 'Šis failas bus sukurtas kaip',
    ],
    
    'edit' => [
        'youre-editing' => 'Jūs redaguojate',
        'will-be-exluded' => 'failą. Visi čia išvardyti failai ar katalogai nebus įtraukti į atsargines kopijas. Šablonai palaikomi naudojant žvaigždutę',
        'you-can-negate' => 'Galite panaikinti ankstesnę taisyklę prieš tai pridėdami šauktuką',
        'save-content' => 'Išsaugoti turinį',
        'create-file' => 'Sukurti failą',
    ],
];