<?php

return [
    'schedules' => 'Tvarkaraščiai',
    'manage-schedules' => 'Tvarkyti tvarkaraščius',
    'create-schedule' => 'Sukurti tvarkaraštį',
    'name' => 'Pavadinimas',
    'last-run-at' => 'Paskutinį kartą vykdyta',
    'next-run-at' => 'Kitas vykdymas',
    'status' => 'Būsena',
    'active' => 'Aktyvus',
    'inactive' => 'Neaktyvus',
    'processing' => 'Vykdoma',
    'manage-schedule' => 'Tvarkyti tvarkaraštį',
    'new-task' => 'Nauja užduotis',
    'run-now' => 'Vykdyti dabar',
    'editBtn' => 'Redaguoti',
    'n/a' => 'nėra',
    'never' => 'niekada',

    'no-schedules' => 'Šiam serveriui nėra sukonfigūruota jokių tvarkaraščių.',
    'ignore-files-folders' => 'Ignoruojami failai ir aplankai',
    'continues-on-failure' => 'Tęsti, nepavykus',
    'later' => 'vėliau',

    'minute' => 'Minutė',
    'hour' => 'Valanda',
    'day' => 'Diena',
    'week' => 'Savaitė',
    'day-of-month' => 'Mėnesio diena',
    'month' => 'Mėnuo',
    'day-of-week' => 'Savaitės diena',

    'deleteTask' => [
        'title' => 'Patvirtinti užduoties ištrynimą',
        'description' => 'Ar tikrai norite ištrinti šią užduotį? Šis veiksmas negali būti atšauktas.',
        'delete' => 'Ištrinti užduotį'
    ],
    'delete' => [
        'title' => 'Ištrinti tvarkaraštį',
        'description' => 'Visos užduotys bus pašalintos, o visi vykdomi procesai bus nutraukti.',
        'delete' => 'Ištrinti'
    ],
    'edit' => [
        'title-1' => 'Redaguoti tvarkaraštį',
        'title-2' => 'Sukurti naują tvarkaraštį',

        'description' => 'Tvarkaraščių sistema palaiko Cronjob sintaksės naudojimą nustatant, kada užduotys turėtų pradėti veikti. Naudokite aukščiau esančius laukelius, kad nurodytumėte, kada šios užduotys turėtų pradėti veikti.',
        
        'name' => 'Tvarkaraščio pavadinimas',
        'name-description' => 'Žmogui suprantamas šio tvarkaraščio identifikatorius.',
        'cheatsheet' => 'Rodyti cheat lapelį',
        'cheatsheet-description' => 'Rodyti cron cheat lapelį su pavyzdžiais',
        'online-when-online' => 'Tik kai serveris veikia',
        'online-when-online-description' => 'Vykdyti šį tvarkaraštį tik tada, kai serveris yra paleistas.',
        'enabled' => 'Tvarkaraštis įjungtas',
        'enabled-description' => 'Šis tvarkaraštis bus vykdomas automatiškai, jei įjungtas.',

        'easy-mode' => 'Lengvas režimas',
        'easy-mode-description' => 'Perjungti į išplėstinį režimą, kad būtų galima konfigūruoti cron nustatymus',
        'easy' => 'Lengvas',
        'advanced' => 'Išplėstinis',

        'save-changes' => 'Išsaugoti pakeitimus',
    ],
    'cheatsheet' => [
        'example' => 'Pavyzdžiai',
        'every-5-minutes' => 'kas 5 minutes',
        'every-hour' => 'kas valandą',
        'hour-range' => 'valandų intervalas',
        'once-a-day' => 'kartą per dieną',
        'every-monday' => 'kiekvieną pirmadienį',
        'special-characters' => 'Specialieji simboliai',
        'any-value' => 'bet kokia reikšmė',
        'value-list-separator' => 'reikšmių sąrašo skirtukas',
        'range-values' => 'reikšmių intervalas',
        'step-values' => 'žingsnio reikšmės',
    ],
    'task' => [
        'message' => 'Atsarginės kopijos užduotis negali būti sukurta, kai serverio atsarginių kopijų limitas nustatytas į 0.',
        'edit-task' => 'Redaguoti užduotį',
        'easy-mode' => 'Lengvas režimas',
        'easy-mode-description' => 'Perjungti į išplėstinį režimą, kad būtų galima konfigūruoti cron nustatymus',
        'easy' => 'Lengvas',
        'advanced' => 'Išplėstinis',

        'save-changes' => 'Išsaugoti pakeitimus',
        'create-task' => 'Sukurti užduotį',
        'action' => 'Veiksmas',
        'send-command' => 'Siųsti komandą',
        'send-power-action' => 'Siųsti maitinimo veiksmą',
        'create-backup' => 'Sukurti atsarginę kopiją',
        'offset' => 'Laiko poslinkis (sekundėmis)',
        'offset-description' => 'Kiek laiko palaukti po ankstesnės užduoties vykdymo, prieš vykdant šią. Jei tai pirmoji tvarkaraščio užduotis, tai nebus taikoma.',
        'payload' => 'Komanda / Veiksmas',
        'ignored-files' => 'Ignoruojami failai',
        'ignored-files-description' => 'Neprivaloma. Įtraukite failus ir aplankus, kurie turėtų būti neįtraukti į šią atsarginę kopiją. Pagal numatytuosius nustatymus bus naudojamas jūsų .pteroignore failo turinys. Jei pasiekėte atsarginių kopijų limitą, seniausia kopija bus pakeista.',
        'start-server' => 'Paleisti serverį',
        'stop-server' => 'Išjungti serverį',
        'restart-server' => 'Paleisti serverį iš naujo',
        'kill-server' => 'Priverstinai sustabdyti serverį',
        'continue-on-failure' => 'Tęsti, nepavykus',
        'continue-on-failure-description' => 'Kitos užduotys bus vykdomos, jei šiai užduočiai nepavyks.',
    ],
];