<?php

return [
    'online' => '온라인',
    'offline' => '오프라인',
    'starting' => '시작 중',
    'stopping' => '정지 중',
    'suspended' => '중지됨',
    'connection-error' => '연결 오류',
    'transferring' => '전송 중',
    'installing' => '설치 중',
    'restoring-backup' => '백업 복원 중',
    'unavailable' => '사용 불가',
    'status' => '상태',
    'CPU' => 'CPU',
    'memory' => '메모리',
    'disk' => '디스크',
    'unlimited' => '무제한',
    'start' => '시작',
    'restart' => '재시작',
    'stop' => '정지',
    'kill' => '프로세스 강제 종료',
    'forcibly-stop-process' => '프로세스 강제 종료',
    'continue' => '계속',
    'forcibly-stopping-alert' => '서버를 강제로 정지하면 데이터 손상의 위험이 있습니다.',
    'cpu-usage' => 'CPU 사용량',
    'memory-usage' => '메모리 사용량',
    'disk-usage' => '디스크 사용량',
    'inbound-outbound' => '수신 / 송신',
    'low-resources' => '자원 부족',
    'low-resources-desc' => '서버 자원이 부족합니다. 플랜을 업그레이드하십시오.',
    'upgrade-server' => '서버 업그레이드',
    'cancel' => '취소',
    'copied-text' => '{{text}}이(가) 클립보드에 복사되었습니다.',
    'showing' => '표시 중',
    'to' => '에서',
    'of' => '의',
    'results' => '결과.',
];
