<?php

return [
    'file-manager' => 'Dosya Yöneticisi',
    'search' => 'Ara',
    'delete' => 'Sil',
    'move' => 'Taşı',
    'archive' => 'Arşivle',
    'unarchive' => 'Arşivi Çıkar',
    'create-directory' => 'Dizin Oluştur',
    'upload' => 'Yükle',
    'new-file' => 'Yeni Dosya',
    'rename' => 'Yeniden Adlandır',
    'permissions' => 'İzinler',
    'copy' => 'Kopyala',
    'download' => 'İndir',
    'update' => 'Güncelle',
    'file-mode' => 'Dosya Modu',
    'you-cant-recover' => 'İçeriği kurtaramazsınız',
    'once-deleted' => 'sildikten sonra.',
    'delete-files' => 'Dosyaları Sil',
    'are-you-sure' => 'Emin misiniz, silmek istiyor musunuz',
    'this-is-permanent-action' => 'Bu kalıcı bir işlemdir ve dosyalar kurtarılamaz.',
    'name' => 'ad',
    'size' => 'boyut',
    'date' => 'tarih',
    'home' => 'ana dizin',
    'container' => 'konteyner',
    'is-empty' => 'Bu dizin boş gibi görünüyor.',
    'is-limited' => 'Bu dizin, tarayıcıda görüntülenmek için çok büyük, çıktıyı ilk 250 dosyaya sınırlıyor.',
    'are-upload-click-to-view' => 'dosya yükleniyor, görmek için tıklayın',
    'cancel-uploads' => 'Yüklemeleri İptal Et',
    'cancel' => 'İptal',
    'close' => 'Kapat',
    'create' => 'Oluştur',
    'file-name' => 'Dosya Adı',
    'file-name-description' => 'Bu dosyanın kaydedilmesi gereken adı girin.',
    'directory-will-be-as' => 'Bu dizin olarak oluşturulacak',
    'rename-description' => 'Bu dosyanın veya klasörün yeni adını ve dizinini, mevcut dizine göre girin.',
    'new-location' => 'Yeni konum',
    'drag-and-drop' => 'Yüklemek için dosyaları sürükleyip bırakın.',

    'edit' => [
        'youre-editing' => 'Şu an düzenliyorsunuz',
        'will-be-excluded' => 'dosyasını. Burada listelenen herhangi bir dosya veya dizin yedeklemelerden hariç tutulacaktır. Yıldız işareti kullanarak joker karakterler desteklenir',
        'you-can-negate' => 'Önceki bir kuralı ünlem işareti ekleyerek yok sayabilirsiniz',
        'save-content' => 'İçeriği Kaydet',
        'create-file' => 'Dosya Oluştur',
    ],
];
