<?php 

return [
    'schedules' => 'Zaman Çizelgeleri',
    'manage-schedules' => 'Zaman çizelgelerini yönet',
    'create-schedule' => 'Zaman çizelgesi oluştur',
    'name' => 'Ad',
    'last-run-at' => 'Son çalışma zamanı',
    'next-run-at' => 'Bir sonraki çalışma zamanı',
    'status' => 'Durum',
    'active' => 'Aktif',
    'inactive' => 'Pasif',
    'processing' => 'İşleniyor',
    'manage-schedule' => 'Zaman çizelgesini yönet',
    'new-task' => 'Yeni Görev',
    'run-now' => 'Şimdi Çalıştır',
    'editBtn' => 'Düzenle',
    'n/a' => 'N/A',
    'never' => 'asla',

    'no-schedules' => 'Bu sunucu için yapılandırılmış bir zaman çizelgesi bulunmamaktadır.',
    'ignore-files-folders' => 'Dosya ve klasörleri Yoksay',
    'continues-on-failure' => 'Başarısızlık Durumunda Devam Ediyor',
    'later' => 'sonra',

    'minute' => 'Dakika',
    'hour' => 'Saat',
    'day' => 'Gün',
    'week' => 'Hafta',
    'day-of-month' => 'Ayın Günü',
    'month' => 'Ay',
    'day-of-week' => 'Haftanın Günü',

    'deleteTask' => [
        'title' => 'Görev Silmeyi Onayla',
        'description' => 'Bu görevi silmek istediğinizden emin misiniz? Bu işlem geri alınamaz.',
        'delete' => 'Görevi Sil'
    ],
    'delete' => [
        'title' => 'Zaman Çizelgesini Sil',
        'description' => 'Tüm görevler kaldırılacak ve çalışan işlemler sona erdirilecektir.',
        'delete' => 'Sil'
    ],
    'edit' => [
        'title-1' => 'Zaman Çizelgesini Düzenle',
        'title-2' => 'Yeni Zaman Çizelgesi Oluştur',

        'description' => 'Zaman çizelgesi sistemi, görevlerin ne zaman başlaması gerektiğini tanımlarken Cronjob sözdizimini destekler. Bu görevlerin ne zaman başlaması gerektiğini belirtmek için yukarıdaki alanları kullanın.',
        
        'name' => 'Zaman Çizelgesi Adı',
        'name-description' => 'Bu zaman çizelgesi için insan tarafından okunabilir bir tanımlayıcı.',
        'cheatsheet' => 'Cron Hile Kağıdını Göster',
        'cheatsheet-description' => 'Bazı örnekler için cron hile kağıdını göster',
        'online-when-online' => 'Sadece Sunucu Çevrimiçi Olduğunda',
        'online-when-online-description' => 'Bu zaman çizelgesi, sunucu çalışır durumdayken yalnızca çalıştırılacaktır.',
        'enabled' => 'Zaman Çizelgesi Etkin',
        'enabled-description' => 'Bu zaman çizelgesi, etkinse otomatik olarak çalıştırılacaktır.',

        'save-changes' => 'Değişiklikleri Kaydet',
    ],
    'cheatsheet' => [
        'example' => 'Örnekler',
        'every-5-minutes' => 'her 5 dakikada bir',
        'every-hour' => 'her saat',
        'hour-range' => 'saat aralığı',
        'once-a-day' => 'günde bir kez',
        'every-monday' => 'her pazartesi',
        'special-characters' => 'Özel Karakterler',
        'any-value' => 'herhangi bir değer',
        'value-list-separator' => 'değer listesi ayırıcısı',
        'range-values' => 'aralık değerleri',
        'step-values' => 'adım değerleri',
    ],
    'task' => [
        'message' => 'Sunucunun yedekleme limiti 0 olarak ayarlandığında bir yedekleme görevi oluşturulamaz.',
        'edit-task' => 'Görevi Düzenle',
        'save-changes' => 'Değişiklikleri Kaydet',
        'create-task' => 'Görev Oluştur',
        'action' => 'Eylem',
        'send-command' => 'Komut Gönder',
        'send-power-action' => 'Güç Eylemi Gönder',
        'create-backup' => 'Yedekleme Oluştur',
        'offset' => 'Zaman Ofseti (saniye cinsinden)',
        'offset-description' => 'Bu görevin çalıştırılmasından önce önceki görevin ne kadar süre beklemesi gerektiğini belirler. Bu, bir zaman çizelgesindeki ilk görevse bu uygulanmaz.',
        'payload' => 'Veri Paketi',
        'ignored-files' => 'Yoksayılan Dosyalar',
        'ignored-files-description' => 'İsteğe bağlı. Bu yedeklemede hariç tutulacak dosya ve klasörleri belirtin. Varsayılan olarak .pteroignore dosyanızın içeriği kullanılacaktır. Yedekleme limitine ulaştıysanız, en eski yedekleme döndürülür.',
        'start-server' => 'Sunucuyu Başlat',
        'stop-server' => 'Sunucuyu Durdur',
        'restart-server' => 'Sunucuyu Yeniden Başlat',
        'kill-server' => 'Sunucuyu Sonlandır',
        'continue-on-failure' => 'Başarısızlık Durumunda Devam Et',
        'continue-on-failure-description' => 'Bu görev başarısız olduğunda gelecekteki görevler çalıştırılacaktır.',
    ],
];
