<?php

return [
    'file-manager' => 'Průzkumník souborů',
    'search' => 'Hledat',
    'delete' => 'Odstranit',
    'move' => 'Přesunout',
    'archive' => 'Archivovat',
    'unarchive' => 'Extrahovat',
    'create-directory' => 'Nová složka',
    'upload' => 'Nahrát',
    'new-file' => 'Nový soubor',
    'rename' => 'Přejmenovat',
    'permissions' => 'Oprávnění',
    'copy' => 'Kopírovat',
    'download' => 'Stáhnout',
    'update' => 'Updatovat',
    'file-mode' => 'File Mode',
    'you-cant-recover' => 'Nebudete moci obnovit obsah',
    'once-deleted' => 'po smazání.',
    'delete-files' => 'Odstranit soubory',
    'are-you-sure' => 'Jste si jistý že chcete smazat tyto soubory?',
    'this-is-permanent-action' => 'Tohle je nevratná akce a soubory nebude možné obnovit.',
    'name' => 'název',
    'size' => 'velikost',
    'date' => 'datum',
    'home' => 'home',
    'container' => 'container',
    'is-empty' => 'Tato složka je prázdná.',
    'is-limited' => 'Tato složka je příliš velká pro zobrazení v prohlížeči, omezíme výstupu na prvních 250 souborů.',
    'are-upload-click-to-view' => 'soubory se nahrávají, klikněte pro zobrazení.',
    'cancel-uploads' => 'Zrušit nahrávání',
    'cancel' => 'Zrušit',
    'close' => 'Zavřít',
    'create' => 'Vytvořit',
    'file-name' => 'Název souboru',
    'file-name-description' => 'Vložte název pod kterým má být soubor uložen.',
    'directory-will-be-as' => 'Tato složka bude vytvořena jako',
    'rename-description' => 'Vložte nový název a složku thoto souboru nebo složky relativní k aktuálnímu umístění.',
    'new-location' => 'Nové umístění',
    'drag-and-drop' => 'Přetáhněte soubory sem pro nahrání.',


    'folders-not-supported' => 'Folder uploads are not supported at this time.',
    'upload-files' => 'Upload Files',
    'folder-too-big' => 'Folder size exceeds 10MB limit. Please select a smaller folder.',
    'upload-folders' => 'Upload Folders',
    'upload-from-url' => 'Upload from URL',
    'filename' => 'Filename',
    'open-code-editor' => 'Open Code Editor',

    'code-editor' => [
        'explorer' => 'Explorer',
        'reload' => 'Reload',
        'new' => 'New',
        'browse-files' => 'Browse Files',
        'save' => 'Save',
        'save-dirty' => 'Save *',
        'saving' => 'Saving...',
        'no-file-selected' => 'No file selected',
        'no-files-found' => 'No files found',
        'loading' => 'Loading...',

        'file-be-created' => 'This file will be created as',
    ],
    
    'edit' => [
        'youre-editing' => 'Upravujete',
        'will-be-exluded' => 'soubor. Jakékoliv soubory nebo složky uvedené zde budou vynechány z záloh. Zástupné znaky jsou podporovány použitím hvězdičky',
        'you-can-negate' => 'Můžete negovat předchozí pravidlo přidáním vykřičníku na začátek.',
        'save-content' => 'Uložit',
        'create-file' => 'Vytvořit soubor',
    ],
];
