<?php

return [
    'file-manager' => 'Průzkumník souborů',
    'search' => 'Hledat',
    'delete' => 'Odstranit',
    'move' => 'Přesunout',
    'archive' => 'Archivovat',
    'unarchive' => 'Extrahovat',
    'create-directory' => 'Nová složka',
    'upload' => 'Nahrát',
    'new-file' => 'Nový soubor',
    'rename' => 'Přejmenovat',
    'permissions' => 'Oprávnění',
    'copy' => 'Kopírovat',
    'download' => 'Stáhnout',
    'update' => 'Updatovat',
    'file-mode' => 'Režim souboru',
    'you-cant-recover' => 'Nebudete moci obnovit obsah',
    'once-deleted' => 'po smazání.',
    'delete-files' => 'Odstranit soubory',
    'are-you-sure' => 'Jste si jistý že chcete smazat tyto soubory?',
    'this-is-permanent-action' => 'Tohle je nevratná akce a soubory nebude možné obnovit.',
    'name' => 'název',
    'size' => 'velikost',
    'date' => 'datum',
    'home' => 'domov',
    'container' => 'kontejner',
    'is-empty' => 'Tato složka je prázdná.',
    'is-limited' => 'Tato složka je příliš velká pro zobrazení v prohlížeči, omezíme výstupu na prvních 250 souborů.',
    'are-upload-click-to-view' => 'soubory se nahrávají, klikněte pro zobrazení.',
    'cancel-uploads' => 'Zrušit nahrávání',
    'cancel' => 'Zrušit',
    'close' => 'Zavřít',
    'create' => 'Vytvořit',
    'file-name' => 'Název souboru',
    'file-name-description' => 'Vložte název pod kterým má být soubor uložen.',
    'directory-will-be-as' => 'Tato složka bude vytvořena jako',
    'rename-description' => 'Vložte nový název a složku thoto souboru nebo složky relativní k aktuálnímu umístění.',
    'new-location' => 'Nové umístění',
    'drag-and-drop' => 'Přetáhněte soubory sem pro nahrání.',


    'folders-not-supported' => 'Nahrávání složek není momentálně podporováno.',
    'upload-files' => 'Nahrát soubory',
    'folder-too-big' => 'Velikost složky přesahuje limit 10 MB. Vyberte prosím menší složku.',
    'upload-folders' => 'Nahrát složky',
    'upload-from-url' => 'Nahrát z URL',
    'filename' => 'Název souboru',
    'open-code-editor' => 'Otevřít editor kódu',

    'code-editor' => [
        'explorer' => 'Průzkumník',
        'reload' => 'Znovu načíst',
        'new' => 'Nový',
        'browse-files' => 'Procházet soubory',
        'save' => 'Uložit',
        'save-dirty' => 'Uložit *',
        'saving' => 'Ukládání...',
        'no-file-selected' => 'Žádný soubor nevybrán',
        'no-files-found' => 'Žádné soubory nenalezeny',
        'loading' => 'Načítání...',

        'file-be-created' => 'Tento soubor bude vytvořen jako',
    ],
    
    'edit' => [
        'youre-editing' => 'Upravujete',
        'will-be-exluded' => 'soubor. Jakékoliv soubory nebo složky uvedené zde budou vynechány z záloh. Zástupné znaky jsou podporovány použitím hvězdičky',
        'you-can-negate' => 'Můžete negovat předchozí pravidlo přidáním vykřičníku na začátek.',
        'save-content' => 'Uložit',
        'create-file' => 'Vytvořit soubor',
    ],
];
