<?php 

return [
    'schedules' => 'Plánovač',
    'manage-schedules' => 'Spravovat spouštěče',
    'create-schedule' => 'Vytvořit spouštěč',
    'name' => 'Název',
    'last-run-at' => 'Naposledy',
    'next-run-at' => 'Nadcházející',
    'status' => 'Stav',
    'active' => 'Aktivní',
    'inactive' => 'Neaktivní',
    'processing' => 'Zpracovává se',
    'manage-schedule' => 'Spravovat úlohu',
    'new-task' => 'Nová úloha',
    'run-now' => 'Provést teď',
    'editBtn' => 'Upravit',
    'n/a' => 'n/a',
    'never' => 'nikdy',

    'no-schedules' => 'Nejsou nastavený žádné spouštěče.',
    'ignore-files-folders' => 'Ignorovat soubory a složky',
    'continues-on-failure' => 'Pokračovat při chybě',
    'later' => 'later',

    'minute' => 'Minut',
    'hour' => 'Hodin',
    'day' => 'Den',
    'week' => 'Týden',
    'day-of-month' => 'Den v měsící',
    'month' => 'Měsíc',
    'day-of-week' => 'Den v týdnu',

    'deleteTask' => [
        'title' => 'Potvrdit smazání úlohy',
        'description' => 'Opravdu chcete smazat tuto úlohu? Tato akce je nevratná.',
        'delete' => 'Odstranit'
    ],
    'delete' => [
        'title' => 'Odstranit spoštěč',
        'description' => 'Všechny úlohy spojené s tímto spoštěčem budou odstraněny a běžíci budou zastaveny. Opravdu chcete pokračovat?',
        'delete' => 'Odstranit'
    ],
    'edit' => [
        'title-1' => 'Upravit spoštěč',
        'title-2' => 'Vytvořit spoštěč',

        'description' => 'Plánovací systém podporuje použití syntaxe Cronjob při definování, kdy by měly úlohy začít běžet. Použijte pole výše k určení, kdy by měly tyto úlohy začít běžet.',

        'name' => 'Název spouštěče',
        'name-description' => 'Člověkem čitelný identifikátor spouštěče. Například: Zálohování na noc',
        'cheatsheet' => 'Zobrazit nápovědu',
        'cheatsheet-description' => 'Zobrazit cron nápovědu pro některé příklady',
        'online-when-online' => 'Pouze pokud je server online',
        'online-when-online-description' => 'Spustí tento příkaz pouze pokud je server online. Pokud je server offline, úloha bude přeskočena.',
        'enabled' => 'Spouštěš je aktivní',
        'enabled-description' => 'Pokud je toto povoleno úkoly spouštěče se spustí automatiky.',

        'save-changes' => 'Uložit',
    ],
    'cheatsheet' => [
        'example' => 'Příklady',
        'every-5-minutes' => 'Každých 5 minut',
        'every-hour' => 'každou hodinu',
        'hour-range' => 'hodinový rozsah',
        'once-a-day' => 'jednou za den',
        'every-monday' => 'každé pondělí',
        'special-characters' => 'Speciální znaky',
        'any-value' => 'jakákoliv hodnota',
        'value-list-separator' => 'oddělovač hodnot',
        'range-values' => 'rozmezí hodnot',
        'step-values' => 'krůčkové hodnoty',
    ],
    'task' => [
        'message' => 'Úloha pro zálohování nemůže být vytvořena pokud je limit záloh 0',
        'edit-task' => 'Uravit úlohu',
        'save-changes' => 'Uložit',
        'create-task' => 'Vytvořit',
        'action' => 'Akce',
        'send-command' => 'Polsat příkaz',
        'send-power-action' => 'Poslat akci napájení',
        'create-backup' => 'Vytvořit zálohu',
        'offset' => 'Časový posun (minuty)',
        'offset-description' => 'Jak dloho po dokončení předchozí úlohy má být tato úloha spuštěna. Pokud je toto první úloha na plánu, nebude toto použito.',
        'payload' => 'Payload',
        'ignored-files' => 'Ignoroané soubory',
        'ignored-files-description' => 'Volitelné. Zahrnuje soubory a složky, které mají být v této záloze vynechány. Výchozí bude použit obsah vašeho souboru .pteroignore. Pokud jste dosáhli limitu záloh, nejstarší záloha bude rotována.',
        'start-server' => 'Spustit server',
        'stop-server' => 'Zastavit server',
        'restart-server' => 'Restartovat srver',
        'kill-server' => 'Kill server',
        'continue-on-failure' => 'Pokračovat při chybě',
        'continue-on-failure-description' => 'Nasledující úlohy se spustí ikdyž tato úloha selže.',
    ],
];
