<?php

return [
    'file-manager' => 'File manager',
    'search' => 'Search',
    'delete' => 'Delete',
    'move' => 'Move',
    'archive' => 'Archive',
    'unarchive' => 'Unarchive',
    'create-directory' => 'Nayi directory banao',
    'upload' => 'Upload',
    'new-file' => 'Nayi file',
    'rename' => 'Rename',
    'permissions' => 'Permissions',
    'copy' => 'Copy',
    'download' => 'Download',
    'update' => 'Update',
    'file-mode' => 'File mode',
    'you-cant-recover' => 'Aap isme rakha data baad me wapas nahi la paoge',
    'once-deleted' => 'Ek baar delete hone ke baad.',
    'delete-files' => 'Files delete karo',
    'are-you-sure' => 'Kya aap sure ho ki aap inhe delete karna chahte ho',
    'this-is-permanent-action' => 'Yeh permanent action hai aur files wapas nahi aayengi.',
    'name' => 'Name',
    'size' => 'Size',
    'date' => 'Date',
    'home' => 'Home',
    'container' => 'Container',
    'is-empty' => 'Yeh directory khaali lag rahi hai.',
    'is-limited' => 'Yeh directory browser me dikhane ke liye bahut badi hai, sirf pehli 250 files dikhayi jayengi.',
    'are-upload-click-to-view' => 'Files upload ho rahi hain, dekhne ke liye click karo',
    'cancel-uploads' => 'Uploads cancel karo',
    'cancel' => 'Cancel',
    'close' => 'Close',
    'create' => 'Create',
    'file-name' => 'File ka naam',
    'file-name-description' => 'Woh naam daalo jisme yeh file save hogi.',
    'directory-will-be-as' => 'Yeh directory is naam se banegi',
    'rename-description' => 'Is file ya directory ka naya naam aur path daalo, current directory ke hisaab se.',
    'new-location' => 'Naya location',
    'drag-and-drop' => 'Files ko yahan drag and drop karke upload karo.',


    'folders-not-supported' => 'Is waqt folder uploads support nahi hote.',
    'upload-files' => 'Files upload karo',
    'folder-too-big' => 'Folder ka size 10MB limit se zyada hai. Please chhota folder choose karo.',
    'upload-folders' => 'Folders upload karo',
    'upload-from-url' => 'URL se upload karo',
    'filename' => 'Filename',
    'open-code-editor' => 'Code editor kholo',

    'code-editor' => [
        'explorer' => 'Explorer',
        'reload' => 'Reload',
        'new' => 'New',
        'browse-files' => 'Files browse karo',
        'save' => 'Save',
        'save-dirty' => 'Save *',
        'saving' => 'Saving...',
        'no-file-selected' => 'Koi file select nahi hai',
        'no-files-found' => 'Koi files nahi mili',
        'loading' => 'Loading...',

        'file-be-created' => 'Yeh file is naam se banegi',
    ],
    
    'edit' => [
        'youre-editing' => 'Aap ek',
        'will-be-exluded' => 'file edit kar rahe ho. Yahan likhi hui koi bhi file ya directory backups se exclude ho jayegi. Wildcards use kar sakte ho',
        'you-can-negate' => 'Aap rule ko negate karne ke liye path ke aage ek exclamation laga sakte ho',
        'save-content' => 'Content save karo',
        'create-file' => 'File banao',
    ],
];
