<?php

return [
    'schedules' => 'Schedules',
    'manage-schedules' => 'Schedules manage karo',
    'create-schedule' => 'Naya schedule banao',
    'name' => 'Name',
    'last-run-at' => 'Last run time',
    'next-run-at' => 'Next run time',
    'status' => 'Status',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'processing' => 'Processing',
    'manage-schedule' => 'Schedule manage karo',
    'new-task' => 'Naya task',
    'run-now' => 'Abhi chalao',
    'editBtn' => 'Edit',
    'n/a' => 'N/A',
    'never' => 'Kabhi nahi',

    'no-schedules' => 'Is server ke liye koi schedule set nahi hai.',
    'ignore-files-folders' => 'Files aur folders ignore karo',
    'continues-on-failure' => 'Fail hone par bhi continue kare',
    'later' => 'Baad me',

    'minute' => 'Minute',
    'hour' => 'Hour',
    'day' => 'Din',
    'week' => 'Week',
    'day-of-month' => 'Mahine ka din',
    'month' => 'Mahina',
    'day-of-week' => 'Hafte ka din',

    'deleteTask' => [
        'title' => 'Task delete karne ki confirm karo',
        'description' => 'Kya aap sure ho ki aap yeh task delete karna chahte ho? Is action ko undo nahi kar sakte.',
        'delete' => 'Task delete karo'
    ],
    'delete' => [
        'title' => 'Schedule delete karo',
        'description' => 'Saare tasks delete ho jayenge aur chal rahe processes bhi band ho jayenge.',
        'delete' => 'Delete',
    ],
    'edit' => [
        'title-1' => 'Schedule edit karo',
        'title-2' => 'Naya schedule banao',

        'description' => 'Schedule system ye decide karne ke liye cron job syntax use karta hai ki tasks kab chalne chahiye. Upar diye fields se batao ki tasks kab start honge.',
        
        'name' => 'Schedule ka naam',
        'name-description' => 'Is schedule ke liye ek simple sa naam.',
        'cheatsheet' => 'Cheatsheet dikhao',
        'cheatsheet-description' => 'Cron cheatsheet ke kuch examples dikhao',
        'online-when-online' => 'Sirf jab server online ho',
        'online-when-online-description' => 'Sirf tab yeh schedule chale jab server chal raha ho.',
        'enabled' => 'Schedule enabled hai',
        'enabled-description' => 'Agar on hai to yeh schedule automatically chalega.',

        'easy-mode' => 'Easy Mode',
        'easy-mode-description' => 'Custom cron config ke liye advanced mode par switch karo',
        'easy' => 'Easy',
        'advanced' => 'Advanced',

        'save-changes' => 'Changes save karo',
    ],
    'cheatsheet' => [
        'example' => 'Examples',
        'every-5-minutes' => 'Har 5 minute',
        'every-hour' => 'Har ghante',
        'hour-range' => 'Ghante ka range',
        'once-a-day' => 'Din me ek baar',
        'every-monday' => 'Har Monday',
        'special-characters' => 'Special characters',
        'any-value' => 'Koi bhi value',
        'value-list-separator' => 'Values list separator',
        'range-values' => 'Range values',
        'step-values' => 'Step values',
    ],
    'task' => [
        'message' => 'Jab server ki backup limit 0 ho to backup task create nahi ho sakta.',
        'edit-task' => 'Task edit karo',
        'easy-mode' => 'Easy Mode',
        'easy-mode-description' => 'Custom cron config ke liye advanced mode par switch karo',
        'easy' => 'Easy',
        'advanced' => 'Advanced',

        'save-changes' => 'Changes save karo',
        'create-task' => 'Task banao',
        'action' => 'Action',
        'send-command' => 'Command bhejo',
        'send-power-action' => 'Power action bhejo',
        'create-backup' => 'Backup banao',
        'offset' => 'Offset (seconds me)',
        'offset-description' => 'Pichhle task ke run hone ke baad is task ko chalane se pehle wait karne ka time. Agar yeh schedule ka pehla task hai to apply nahi hoga.',
        'payload' => 'Payload',
        'ignored-files' => 'Ignore ki hui files',
        'ignored-files-description' => 'Optional. Is backup me ignore ki jane wali files aur folders yahan likho. Khaali chhodne par .pteroignore file ka content use hoga. Agar aap backup limit tak pahunch gaye ho, to sabse purana backup delete ho jayega.',
        'start-server' => 'Server start karo',
        'stop-server' => 'Server stop karo',
        'restart-server' => 'Server restart karo',
        'kill-server' => 'Server force stop karo',
        'continue-on-failure' => 'Fail hone par bhi aage chalao',
        'continue-on-failure-description' => 'Is task ke fail hone par bhi next tasks run hote rahenge.',
    ],
];
