<?php

return [
    'online' => 'Online',
    'offline' => 'Offline',
    'starting' => 'Memulai',
    'stopping' => 'Menghentikan',
    'suspended' => 'Ditangguhkan',
    'connection-error' => 'Error Koneksi',
    'transferring' => 'Mentransfer',
    'installing' => 'Menginstal',
    'restoring-backup' => 'Memulihkan Cadangan',
    'unavailable' => 'Tidak Tersedia',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Memory',
    'disk' => 'Disk',
    'unlimited' => 'Tak Terbatas',
    'start' => 'Mulai',
    'restart' => 'Restart',
    'stop' => 'Berhenti',
    'kill' => 'Hentikan Paksa',
    'forcibly-stop-process' => 'Hentikan Proses Paksa',
    'continue' => 'Lanjutkan',
    'forcibly-stopping-alert' => 'Menghentikan paksa server dapat menyebabkan korupsi data.',
    'cpu-usage' => 'Penggunaan CPU',
    'memory-usage' => 'Penggunaan Memory',
    'disk-usage' => 'Penggunaan Disk',
    'inbound-outbound' => 'Masuk / Keluar',
    'low-resources' => 'Sumber Daya Rendah',
    'low-resources-desc' => 'Server Anda kekurangan sumber daya, pastikan untuk meningkatkan paket Anda',
    'upgrade-server' => 'Upgrade Server',
    'cancel' => 'Batal',
    'copied-text' => 'Menyalin {{text}} ke clipboard.',
    'showing' => 'Menampilkan',
    'to' => 'ke',
    'of' => 'dari',
    'results' => 'hasil.',
];
