<?php

return [
    'file-manager' => 'Manager de Fisiere',
    'search' => 'Cauta',
    'delete' => 'Sterge',
    'move' => 'Muta',
    'archive' => 'Arhiveaza',
    'unarchive' => 'Dezarhiveaza',
    'create-directory' => 'Creaza Director',
    'upload' => 'Incarcati',
    'new-file' => 'Fisier Nou',
    'rename' => 'Redenumeste',
    'permissions' => 'Permisiuni',
    'copy' => 'Copiere',
    'download' => 'Descarcati',
    'update' => 'Actualizare',
    'file-mode' => 'Modul Fisierului',
    'you-cant-recover' => 'Nu veti putea recupera continutul',
    'once-deleted' => 'o data sters.',
    'delete-files' => 'Se sterg fisierele',
    'are-you-sure' => 'Esti sigur ca vrei sa stergi?',
    'this-is-permanent-action' => 'Aceasta actiune este permanenta si nu poate fi recuperat.',
    'name' => 'nume',
    'size' => 'marime',
    'date' => 'data',
    'home' => 'acasa',
    'container' => 'container',
    'is-empty' => 'Acest director se pare ca este gol.',
    'is-limited' => 'Acest director este prea mare pentru a fi afisat in browser, limitand rezultatul la primele 250 de fisiere.',
    'are-upload-click-to-view' => 'fisierele se incarca, apasa sa vezi',
    'cancel-uploads' => 'Anuleaza Incarcarile',
    'cancel' => 'Anuleaza',
    'close' => 'Inchide',
    'create' => 'Creaza',
    'file-name' => 'Nume Fisier',
    'file-name-description' => 'Introdu numele cu care acest fisier ar trebui sa fie salvat.',
    'directory-will-be-as' => 'Directorul va fi salvat ca',
    'rename-description' => 'Introdu noul nume si directorul acestui fisier sau folder, in raport cu directorul curent.',
    'new-location' => 'Locatie Noua',
    'drag-and-drop' => 'Trage si plaseaza fisiere pentru a incarca.',

    'edit' => [
        'youre-editing' => 'Editezi un',
        'will-be-exluded' => 'fisier. Orice fisiere sau directoare enumerate aici vor fi excluse din copia de rezerva. Wildcard-urile sunt acceptate prin utilizarea unui asterisk',
        'you-can-negate' => 'Puteti anula o regula anterioara adaugand inainte un semn de exclamare',
        'save-content' => 'Salveaza Contentul',
        'create-file' => 'Creaza Fisier',
    ],
];
