<?php 

return [
    'schedules' => 'Programe',
    'manage-schedules' => 'Gestioneaza Programarile',
    'create-schedule' => 'Creaza o Programare',
    'name' => 'Nume',
    'last-run-at' => 'Ultima folosire la',
    'next-run-at' => 'Urmatoarea folosire la',
    'status' => 'Status',
    'active' => 'Activ',
    'inactive' => 'Inactiv',
    'processing' => 'Se proceseaza',
    'manage-schedule' => 'Gestioneaza Programarile',
    'new-task' => 'Nou Task',
    'run-now' => 'Incepe Acum',
    'editBtn' => 'Editeaza',
    'n/a' => 'n/a',
    'never' => 'niciodata',

    'no-schedules' => 'Nu sunt programari create pentru acest server.',
    'ignore-files-folders' => 'Se ignora fisierele si folderele',
    'continues-on-failure' => 'Se continua intr-un esec',
    'later' => 'mai tarziu',

    'minute' => 'Minut',
    'hour' => 'Ora',
    'day' => 'Zi',
    'week' => 'Saptamana',
    'day-of-month' => 'Zi din luna',
    'month' => 'Luna',
    'day-of-week' => 'Zi din saptamana',

    'deleteTask' => [
        'title' => 'Confirma stergerea taskului',
        'description' => 'Esti sigur ca vrei sa stergi acest task? Aceasta actiune nu poate fi anulata.',
        'delete' => 'Sterge Task'
    ],
    'delete' => [
        'title' => 'Sterge Programarea',
        'description' => 'Toate sarcinile vor fi eliminate si orice proces care ruleaza va fi incheiat.',
        'delete' => 'Sterge'
    ],
    'edit' => [
        'title-1' => 'Editeaza Programarea',
        'title-2' => 'Creaza o Programare',

        'description' => 'Sistemul de planificare accepta utilizarea sintaxei Cronjob la definirea momentului in care sarcinile ar trebui sa inceapa sa ruleze. Utilizeaza campurile de mai sus pentru a specifica cand ar trebui sa inceapa rularea sarcinilor.',
        
        'name' => 'Numele programarii',
        'name-description' => 'Un identificator care poate fi citit de om pentru acest program.',
        'cheatsheet' => 'Afiseaza Cheatsheet',
        'cheatsheet-description' => 'Afiseaza Cheatsheet-ul cron pentru cateva exemple',
        'online-when-online' => 'Doar cand server-ul este Online',
        'online-when-online-description' => 'Executati acest program numai cand serverul este in stare de rulare.',
        'enabled' => 'Programare Pornita',
        'enabled-description' => 'Aceasta programare va fi executata automat daca este activa.',

        'save-changes' => 'Salveaza schimbarile',
    ],
    'cheatsheet' => [
        'example' => 'Exemple',
        'every-5-minutes' => 'la fiecare 5 minute',
        'every-hour' => 'in fiecare ora',
        'hour-range' => 'interval orar',
        'once-a-day' => 'o data pe zi',
        'every-monday' => 'in fiecare luni',
        'special-characters' => 'Caractere Speciale',
        'any-value' => 'orice valoare',
        'value-list-separator' => 'separator de liste de valori',
        'range-values' => 'valorile intervalului',
        'step-values' => 'valorile pasului',
    ],
    'task' => [
        'message' => 'O sarcina de rezerva nu poate fi creata cand limita de rezerva a serverului este setata la 0.',
        'edit-task' => 'Editeaza Task-ul',
        'save-changes' => 'Se salveaza schimbarile',
        'create-task' => 'Creaza Task',
        'action' => 'Actiune',
        'send-command' => 'Trimite comanda',
        'send-power-action' => 'Trimite o actiune de putere',
        'create-backup' => 'Creaza o copie de rezerva',
        'offset' => 'Decalaj de timp (in secunde)',
        'offset-description' => 'Cantitatea de timp de asteptare dupa executarea sarcinii anterioare inainte de a rula aceasta. Daca aceasta este prima sarcina dintr-un program, aceasta nu va fi aplicata.',
        'payload' => 'Incarcatura Utila',
        'ignored-files' => 'Fisiere Ignorate',
        'ignored-files-description' => 'Optional. Includeti fisierele si folderele care trebuie excluse in aceasta copie de rezerva. In mod explicit, continutul fisierului tau .pteroignore va fi utilizat. Daca ati atins limita de rezerva, cea mai veche copie de rezerva va fi rotita',
        'start-server' => 'Se porneste serverul',
        'stop-server' => 'Se opreste serverul',
        'restart-server' => 'Se restarteaza serverul',
        'kill-server' => 'Inchideti serverul',
        'continue-on-failure' => 'Se continua in esec',
        'continue-on-failure-description' => 'Sarcinile viitoare vor fi executate atunci cand aceasta sarcina esueaza.',
    ],
];
