<?php

return [
    'file-manager' => 'Manajer File',
    'search' => 'Cari',
    'delete' => 'Hapus',
    'move' => 'Pindahkan',
    'archive' => 'Arsip',
    'unarchive' => 'Ekstrak Arsip',
    'create-directory' => 'Buat Direktori',
    'upload' => 'Unggah',
    'new-file' => 'File Baru',
    'rename' => 'Ubah Nama',
    'permissions' => 'Izin',
    'copy' => 'Salin',
    'download' => 'Unduh',
    'update' => 'Perbarui',
    'file-mode' => 'Mode File',
    'you-cant-recover' => 'Anda tidak akan dapat mengembalikan isi dari',
    'once-deleted' => 'setelah dihapus.',
    'delete-files' => 'Hapus File',
    'are-you-sure' => 'Apakah Anda yakin ingin menghapus',
    'this-is-permanent-action' => 'Ini adalah tindakan permanen dan file tidak dapat dikembalikan.',
    'name' => 'nama',
    'size' => 'ukuran',
    'date' => 'tanggal',
    'home' => 'rumah',
    'container' => 'kontainer',
    'is-empty' => 'Direktori ini tampaknya kosong.',
    'is-limited' => 'Direktori ini terlalu besar untuk ditampilkan di browser, batasan keluaran hingga 250 file pertama.',
    'are-upload-click-to-view' => 'file sedang diunggah, klik untuk melihat',
    'cancel-uploads' => 'Batalkan Unggahan',
    'cancel' => 'Batal',
    'close' => 'Tutup',
    'create' => 'Buat',
    'file-name' => 'Nama File',
    'file-name-description' => 'Masukkan nama yang harus digunakan untuk menyimpan file ini.',
    'directory-will-be-as' => 'Direktori ini akan dibuat sebagai',
    'rename-description' => 'Masukkan nama dan direktori baru dari file atau folder ini, relatif terhadap direktori saat ini.',
    'new-location' => 'Lokasi Baru',
    'drag-and-drop' => 'Seret dan lepas file untuk diunggah.',

    'edit' => [
        'youre-editing' => 'Anda sedang mengedit',
        'will-be-exluded' => 'file. Semua file atau direktori yang tercantum di sini akan dikecualikan dari cadangan. Wildcards didukung dengan menggunakan tanda asterisk',
        'you-can-negate' => 'Anda dapat meniadakan aturan sebelumnya dengan menambahkan tanda seru pada awalnya',
        'save-content' => 'Simpan Konten',
        'create-file' => 'Buat File',
    ],
];
