<?php

return [
    'schedules' => 'Jadwal',
    'manage-schedules' => 'Kelola jadwal',
    'create-schedule' => 'Buat Jadwal',
    'name' => 'Nama',
    'last-run-at' => 'Terakhir dijalankan pada',
    'next-run-at' => 'Akan dijalankan pada',
    'status' => 'Status',
    'active' => 'Aktif',
    'inactive' => 'Nonaktif',
    'processing' => 'Diproses',
    'manage-schedule' => 'Kelola jadwal',
    'new-task' => 'Tugas Baru',
    'run-now' => 'Jalankan Sekarang',
    'editBtn' => 'Edit',
    'n/a' => 'n/a',
    'never' => 'tidak pernah',

    'no-schedules' => 'Tidak ada jadwal yang dikonfigurasi untuk server ini.',
    'ignore-files-folders' => 'Menyembunyikan file & folder',
    'continues-on-failure' => 'Melanjutkan saat Gagal',
    'later' => 'nanti',

    'minute' => 'Menit',
    'hour' => 'Jam',
    'day' => 'Hari',
    'week' => 'Minggu',
    'day-of-month' => 'Hari dalam bulan',
    'month' => 'Bulan',
    'day-of-week' => 'Hari dalam minggu',

    'deleteTask' => [
        'title' => 'Konfirmasi penghapusan tugas',
        'description' => 'Apakah Anda yakin ingin menghapus tugas ini? Tindakan ini tidak dapat dibatalkan.',
        'delete' => 'Hapus Tugas'
    ],
    'delete' => [
        'title' => 'Hapus Jadwal',
        'description' => 'Semua tugas akan dihapus dan semua proses yang sedang berjalan akan dihentikan.',
        'delete' => 'Hapus'
    ],
    'edit' => [
        'title-1' => 'Edit jadwal',
        'title-2' => 'Buat jadwal baru',

        'description' => 'Sistem jadwal mendukung penggunaan sintaks Cronjob untuk menentukan kapan tugas harus mulai berjalan. Gunakan bidang di atas untuk menentukan kapan tugas-tugas ini harus mulai berjalan.',
        
        'name' => 'Nama jadwal',
        'name-description' => 'Identifikasi yang mudah dibaca untuk jadwal ini.',
        'cheatsheet' => 'Tampilkan Lembar Tips',
        'cheatsheet-description' => 'Tampilkan lembar tips cron untuk beberapa contoh',
        'online-when-online' => 'Hanya Ketika Server Aktif',
        'online-when-online-description' => 'Hanya jalankan jadwal ini ketika server berada dalam keadaan aktif.',
        'enabled' => 'Jadwal Diaktifkan',
        'enabled-description' => 'Jadwal ini akan dijalankan secara otomatis jika diaktifkan.',

        'save-changes' => 'Simpan perubahan',
    ],
    'cheatsheet' => [
        'example' => 'Contoh',
        'every-5-minutes' => 'setiap 5 menit',
        'every-hour' => 'setiap jam',
        'hour-range' => 'rentang jam',
        'once-a-day' => 'sekali sehari',
        'every-monday' => 'setiap hari Senin',
        'special-characters' => 'Karakter Khusus',
        'any-value' => 'semua nilai',
        'value-list-separator' => 'pemisah daftar nilai',
        'range-values' => 'nilai rentang',
        'step-values' => 'nilai langkah',
    ],
    'task' => [
        'message' => 'Tugas cadangan tidak dapat dibuat ketika batas cadangan server diatur ke 0.',
        'edit-task' => 'Edit Tugas',
        'save-changes' => 'Simpan Perubahan',
        'create-task' => 'Buat Tugas',
        'action' => 'Aksi',
        'send-command' => 'Kirim perintah',
        'send-power-action' => 'Kirim tindakan daya',
        'create-backup' => 'Buat cadangan',
        'offset' => 'Jeda waktu (dalam detik)',
        'offset-description' => 'Jumlah waktu untuk menunggu setelah tugas sebelumnya dieksekusi sebelum menjalankan yang ini. Jika ini adalah tugas pertama pada jadwal, ini tidak akan diterapkan.',
        'payload' => 'Payload',
        'ignored-files' => 'File yang Diabaikan',
        'ignored-files-description' => 'Opsional. Sertakan file dan folder yang akan dikecualikan dalam cadangan ini. Secara default, konten file .pteroignore Anda akan digunakan. Jika Anda mencapai batas cadangan Anda, cadangan tertua akan diputar.',
        'start-server' => 'Mulai server',
        'stop-server' => 'Hentikan server',
        'restart-server' => 'Restart server',
        'kill-server' => 'Akhiri server',
        'continue-on-failure' => 'Lanjutkan saat Gagal',
        'continue-on-failure-description' => 'Tugas-tugas selanjutnya akan dijalankan ketika tugas ini gagal.',
    ],
];
