<?php

return [
    'online' => 'Aktiv',
    'offline' => 'Inaktiv',
    'starting' => 'Startar',
    'stopping' => 'Stoppar',
    'suspended' => 'Avstängd',
    'connection-error' => 'Anslutningsfel',
    'transferring' => 'Överför',
    'installing' => 'Installerar',
    'restoring-backup' => 'Återställer säkerhetskopia',
    'unavailable' => 'Inte tillgänglig',
    'status' => 'Status',
    'CPU' => 'CPU',
    'memory' => 'Minne',
    'disk' => 'Disk',
    'unlimited' => 'Obegränsat',
    'start' => 'Start',
    'restart' => 'Omstart',
    'stop' => 'Stop',
    'kill' => 'Döda',
    'forcibly-stop-process' => 'Tvångsstopp av processen',
    'continue' => 'Fortsätta',
    'forcibly-stopping-alert' => 'Att tvångsstoppa en server kan leda till datakorruption.',
    'cpu-usage' => 'CPU Användning',
    'memory-usage' => 'Memory Användning',
    'disk-usage' => 'Disk Användning',
    'inbound-outbound' => 'Inkommande  / Utgående',
    'low-resources' => 'Låg på resurser',
    'low-resources-desc' => 'Din server har ont om resurser, se till att uppgradera din plan',
    'upgrade-server' => 'Uppgradera server',
    'cancel' => 'Avbryt',
    'copied-text' => 'Kopierade {{text}} till urklipp.',
    'showing' => 'Visar',
    'to' => 'till',
    'of' => 'av',
    'results' => 'resultat.',
];
